### ISSUE TITLE
Epic: enhance the catalog CI

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/catalog#102]
This issue represent an Epic to track work around the CI for catalog.

- Add more simple validation (like `yamllint`): #101
- Add execution tests as much as possible: #103 
- Add continuous tests (validation and execution) on a daily or weekly basis

**Comment by chmouel** [comment]
You can add #103 for the second bullet,

I am not sure I understand your point for : 

`Add continuous tests (validation and execution) on a daily or weekly basis`

why daily, weekly and not just on every PR ?

**Comment by vdemeester** [comment]
This would be to help see how stable or not those task are, and detect early failure if, for some reason, the image is updated and doesn't work anymore in that task for example.
