### ISSUE TITLE
RFE: Add ssl-ca-directory workspace to git-cli Task

### ISSUE THREAD

**Issue by AaronJaegerVA** [tektoncd/catalog#1024]
# Expected Behavior
I would like to add the `ssl-ca-directory` workspace to `the git-cli` Task so it functions like the `git-clone` Task does. 

# Actual Behavior
Doing `git push...` with the `git-cli` Task results in error messages like `fatal: unable to access 'https://gitserver.com/ORG/repo.git/': SSL certificate problem: unable to get local issuer certificate` when connecting to private Git servers with private CA-signed certificates.

# Steps to Reproduce the Problem

1. Use `git-cli` with a `GIT_SCRIPT` parameter containing `git push https://private-git-server.com` against a private Git server with a private CA-signed certificate

# Additional Info
Using `git-cli` v0.3

**Comment by the-it-jaeger** [comment]
/remove-lifecycle rotten 

Enterprise customers care about and demand security. Please consider this feature.

**Comment by the-it-jaeger** [comment]
/remove-lifecycle stale

Bumping for enterprise users again. I wonder if code from another Task that implements the ssl-ca-directory workspace would be an easy fix.
