### ISSUE TITLE
`git-clone` `0.7` --> `0.8` is not compatible with many linux installations

### ISSUE THREAD

**Issue by bendory** [tektoncd/catalog#1044]
# Expected Behavior

`git-clone` task succeeds

# Actual Behavior

`git-clone` task fails

# Steps to Reproduce the Problem

1. `kubectl apply -f pipeline.yaml` from the attached [repro.zip](https://github.com/tektoncd/catalog/files/9305481/repro.zip)
2. `kubectl create -f pipelinerun.yaml` from [repro.zip](https://github.com/tektoncd/catalog/files/9305481/repro.zip)
3. With `git-clone` version `0.7` it succeeds
4. With `git-clone` version `0.8` it fails

# Additional Info

The failure occurs after this log line:
`[fetch-source : clone] + rm -rf /workspace/output//lost+found`
which I assume is because https://github.com/tektoncd/catalog/pull/1034 has `git-clone` executing as a non-root user.

Here is the [code being executed at that time](https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.8/git-clone.yaml#L199-L216).

I tried working around this issue by tweaking the params in my `pipeline.yaml`:
```
    params:
    - name: deleteExisting
      value: "false"
```

But that just moves the error over to `git-init`:

```
[clone] + /ko-app/git-init '-url=https://github.com/bendory/mini-true.git' '-revision=' '-refspec=' '-path=/workspace/output/' '-sslVerify=true' '-submodules=true' '-depth=1' '-sparseCheckoutDirectories='
[clone] {"level":"error","ts":1660183685.4823325,"caller":"git/git.go:55","msg":"Error running git [init /workspace/output/]: exit status 1\n/workspace/output/.git: Permission denied\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:55\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:84\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:225"}
[clone] {"level":"fatal","ts":1660183685.4831095,"caller":"git-init/main.go:54","msg":"Error fetching git repository: exit status 1","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:225"}
```

**Comment by bendory** [comment]
@concaf

**Comment by tonyhsuclrous** [comment]
Same issue when trying [How-to Guides](https://tekton.dev/docs/how-to-guides/clone-repository/#run-the-pipeline) of Tekton official documentation.

Can't use
```
tkn hub install task git-clone
```

Need to use
```
kubectl apply -f \
https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.6/git-clone.yaml
```

**Comment by vdemeester** [comment]
Quick "side" note to this issue, different version of a Task do not necessary need to be backwards compatible. We (catalog maintainers) are not making this guarantee, and the version are even there for this cases (to be able to break backward compatibilities). This is similar to oci images, … nothing really tells you that tag 0.1 behavior will be backward compatible with 0.2, …

**Comment by tonyhsuclrous** [comment]
Thank you for your clarification.

**Comment by bendory** [comment]
@vdemeester That's fair -- but I *do* think catalog tasks want to maintain compatibility with standard unix / linux k8s setups where a PVC is likely to have a `lost+found` directory.

**Comment by msoranno** [comment]
Hi, same here, 
**fatal: cannot mkdir /workspace/output/rbaccfg: Permission denied**

without `SecurityContext` works just fine.

Output with 0.8 as is:
```
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ CHECKOUT_DIR=/workspace/output/rbaccfg
+ '[' true '=' true ]
+ cleandir
+ '[' -d /workspace/output/rbaccfg ]
+ test -z 
+ test -z 
+ test -z 
+ /ko-app/git-init '-url=git@github.kyndryl.net:iscp-dev-eu/iscp-x-rbac-cfg-lab-eu.git' '-revision=develop' '-refspec=' '-path=/workspace/output/rbaccfg' '-sslVerify=true' '-submodules=true' '-depth=1' '-sparseCheckoutDirectories='
{"level":"error","ts":1660659650.9322565,"caller":"git/git.go:55","msg":"Error running git [init /workspace/output/rbaccfg]: exit status 128\nfatal: cannot mkdir /workspace/output/rbaccfg: Permission denied\n","stacktrace":"[github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:55\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:84\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:225](http://github.com/tektoncd/pipeline/pkg/git.run/n/tgithub.com/tektoncd/pipeline/pkg/git/git.go:55/ngithub.com/tektoncd/pipeline/pkg/git.Fetch/n/tgithub.com/tektoncd/pipeline/pkg/git/git.go:84/nmain.main/n/tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53/nruntime.main/n/truntime/proc.go:225)"}
{"level":"fatal","ts":1660659651.063446,"caller":"git-init/main.go:54","msg":"Error fetching git repository: exit status 128","stacktrace":"main.main\n\[tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:225](http://tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54/nruntime.main/n/truntime/proc.go:225)"}
```

**Comment by vdemeester** [comment]
> @vdemeester That's fair -- but I _do_ think catalog tasks want to maintain compatibility with standard unix / linux k8s setups where a PVC is likely to have a `lost+found` directory.

Indeed. I am not stating this is good and completely normal that it breaks from one version to another, just that we don't make that guarantee 🙃.

The trick here is : we are trying to make everything run as user as much as possible — which coming from a place where all runs as root by default, is bound to break more often than we would like to. PVCs and unix rights is somewhat convoluted (see https://stackoverflow.com/questions/51390789/kubernetes-persistent-volume-claim-mounted-with-wrong-gid) which makes this a bit hard to get it right. Maybe this changes was too optimistic though 🙃

**Comment by concaf** [comment]
I will take a look at this tomorrow, sorry for breaking stuff 🧯🔥

**Comment by concaf** [comment]
@tonyhsuclrous updated how-to guide here - https://github.com/tektoncd/website/pull/425

**Comment by tonyhsuclrous** [comment]
In order to have `ssh-directory` working as expected, `userHome` need to be set as shown below.

```
    - name: userHome
      value: "/home/nonroot"
```

**Comment by concaf** [comment]
@tonyhsuclrous ah, or we might have to mess with `/etc/ssh/ssh_config` to change where ssh looks for those files; can you open a separate issue for this?

**Comment by tonyhsuclrous** [comment]
New issue has been created. https://github.com/tektoncd/catalog/issues/1052

**Comment by darktempla** [comment]
> > @vdemeester That's fair -- but I _do_ think catalog tasks want to maintain compatibility with standard unix / linux k8s setups where a PVC is likely to have a `lost+found` directory.
> 
> Indeed. I am not stating this is good and completely normal that it breaks from one version to another, just that we don't make that guarantee 🙃.
> 
> The trick here is : we are trying to make everything run as user as much as possible — which coming from a place where all runs as root by default, is bound to break more often than we would like to. PVCs and unix rights is somewhat convoluted (see https://stackoverflow.com/questions/51390789/kubernetes-persistent-volume-claim-mounted-with-wrong-gid) which makes this a bit hard to get it right. Maybe this changes was too optimistic though 🙃

Agree with this but the whole point of semantic versioning is to signal a breaking change has been introduced. So the author could have bumped from say a minor (0.7) to a major (1.0) version for example.

I have had the same issue with 0.8+0.9 versions. Version 0.7 is working as highlighted above.

**Comment by vdemeester** [comment]
> Agree with this but the whole point of semantic versioning is to signal a breaking change has been introduced. So the author could have bumped from say a minor (0.7) to a major (1.0) version for example.
> 
> I have had the same issue with 0.8+0.9 versions. Version 0.7 is working as highlighted above.

Very valid point 🙃. This is something we need to make sure we get right when moving towards the git-based catalogs.
