### ISSUE TITLE
blue-green-deploy task doesn't work for deployments not in the same namespace 

### ISSUE THREAD

**Issue by makeittotop** [tektoncd/catalog#1050]
# Expected Behavior
The blue-green-deploy task should be passed the namespace as a param alongside other params., so that it could run an operation in that namespace.

# Actual Behavior
Currently the task assumes the deployment lives in the same namespace as the pipeline is run from.

# Steps to Reproduce the Problem

1. Pass in a deployment manifest yaml to the task which has workload in a namespace other than the current one.
2. The task will assume that the deployment is in the same namespace , and will start querying for that deployment blocking indefintely. https://github.com/tektoncd/catalog/blob/main/task/blue-green-deploy/0.1/blue-green-deploy.yaml#L82 

# Additional Info

**Comment by vinamra28** [comment]
@makeittotop makes sense. Do you wish to send a fix for this ?
