### ISSUE TITLE
[Request] Have a task that suports ansible tower-cli commands

### ISSUE THREAD

**Issue by raffamendes** [tektoncd/catalog#106]
# Feature Request

The goal of this request is to have a task for executing tower-cli commands the same way the openshift client task does.

I'm actually willing to create this task, but I never contributed before.

**Comment by vdemeester** [comment]
/kind feature
@raffamendes you can create a PR adding it :angel: Take inspiration from the other tasks present :angel:

**Comment by vdemeester** [comment]
#122 is merged, we can close this one :wink: 
/close
