### ISSUE TITLE
Stackrox/ACS Task using deprecated option

### ISSUE THREAD

**Issue by raffamendes** [tektoncd/catalog#1064]
# Expected Behavior
Using Stackrox/ACS task to scan a image, it shows a warning message that the flag --format has been deprecated, it should change to --output
```console
Getting roxctl
Flag --format has been deprecated, please use --output/-o to specify the output format. NOTE: The new JSON / CSV format contains breaking changes, make sure you adapt to the new structure before migrating.
```
# Actual Behavior
Use the --output flag as indicated by the error message
# Steps to Reproduce the Problem

1.Create a task in any pipeline and pass the necessary secret data
2.Execute the pipeline and get the error as shown in the log snippet above

# Additional Info

Will submit a PR shortly to address this.

**Comment by raffamendes** [comment]
If possible can someone assign me this issue?

**Comment by vdemeester** [comment]
/assign @raffamendes 
(Note, that you can comment `/assign` and it would automtically assign yourself)
