### ISSUE TITLE
buildah: Need input parameter for build context

### ISSUE THREAD

**Issue by NicolasRouquette** [tektoncd/catalog#112]
# Expected Behavior

Suppose we have a repository like this:

`./foo/Dockerfile`
`./foo/bar`
`./foo/bar/Makefile`

where `./foo/Dockerfile` has:

```
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install make
COPY . /app
RUN make -f /app/bar/Makefile
```

In order to build this properly, there should be an input parameter available to specify the build context as `./foo`.

# Actual Behavior

However, the build command is currently:

```
    command: ['buildah', 'bud', '--tls-verify=$(inputs.params.TLSVERIFY)', '--layers', '-f', '$(inputs.params.DOCKERFILE)', '-t', '$(outputs.resources.image.url)', '.']
```

There is currently no way to specify the build context in a `TaskRun`.

# Steps to Reproduce the Problem

# Additional Info

**Comment by piyush-garg** [comment]
Duplicate of #170
