### ISSUE TITLE
Migrate off `pipelineResources` for Catalog Tasks

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/catalog#1134]
Since the  `pipelineResources` are going to be removed in pipeline _v0.45_  as designed in [TEP074](https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md) and according to [deprecation.md](https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md),  _(some have already been removed eg. [cloudevent ](https://github.com/tektoncd/pipeline/pull/5995)and [cluster](https://github.com/tektoncd/pipeline/pull/5996) PipelineResources)_, we need to migrate off the `pipelineResources` for the related catalog tasks that are related with the `pipelineResources`.

Related issue: [Handle PipelineResources when swapping v1 to the storage version #5967](https://github.com/tektoncd/pipeline/issues/5967)

cc @vdemeester @vinamra28 @QuanZhang-William

**Comment by JeromeJu** [comment]
cc @vdemeester @vinamra28 @QuanZhang-William

**Comment by JeromeJu** [comment]
Also please feel free to comment in the original issue about the way forward for deprecating the images regarding `pipelineResources`. Thanks!

**Comment by QuanZhang-William** [comment]
Thanks @JeromeJu!

The [git-init](https://github.com/tektoncd/pipeline/tree/main/cmd/git-init)  image is used in the following Verified Catalogs:
- [git-clone](https://github.com/tektoncd/catalog/tree/main/task/git-clone)
- [git-batch-merge](https://github.com/tektoncd/catalog/tree/main/task/git-batch-merge)

The source code will be maintained in a separate repo in [tektoncd-catalog](https://github.com/tektoncd-catalog) org.

The current [central catalog repo](https://github.com/tektoncd/catalog) will be archived after the Verified Catalog migration is completed. We will send notice to the community catalog authors to migrate their resources off the central repo, and it is up to the authors to decide how do they want to host the images used in their catalog.
