### ISSUE TITLE
Simple Pipeline Example Was Removed

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/catalog#1150]
# Expected Behavior

The simple pipeline used in the git resolver example should exist.

# Actual Behavior

Simple pipeline does not exist, and therefore it can't be resolved.

# Steps to Reproduce the Problem

Try applying the PipelineRun in https://tekton.dev/docs/pipelines/git-resolver/

# Additional Info

Relevant doc: https://tekton.dev/docs/pipelines/git-resolver/

**Comment by vdemeester** [comment]
cc @abayer 
This used to refers scott's repository but this is gone now. I think we moved it *blindly* to target `tektoncd/catalog`, but as far as I know, this `simple-pipeline` was never in this repository in the first place. I would definitely not push towards having it in the repository either. We should just change the git resolvers doc to point to a `simple-pipeline` defined in `tektoncd/pipeline` itself.
