### ISSUE TITLE
Using Kaniko v1.9.2 executor

### ISSUE THREAD

**Issue by mchutani-CS** [tektoncd/catalog#1158]
# Expected Behavior

The Task should be able to run with the latest Kaniko image: `gcr.io/kaniko-project/executor:v1.9.2@sha034f15e6fe235490e64a4173d02d0a41f61382450c314fffed9b8ca96dff66b2`

# Actual Behavior
Error with running the Task

Status: `CouldntGetTask`
Logs: 
```
 Warning  Failed         7m34s  TaskRun  failed to create task run pod "build-push-pipeline-run-1xsc5m-build-push": translating TaskSpec to Pod: duplicate unique image found for platform: unknown/unknown: found sha256:36cd9b9af686787a290372e9c7e4d5b27cd02503248d5a289262d6772905a2ec and sha256:a1585c528f713d20b357a3fd7be7e02fad16a3a6efa │
│ 1abece583591f0463addd. Maybe missing or invalid Task default/kaniko
```

# Steps to Reproduce the Problem

1. Fetch the yaml file from here: https://github.com/tektoncd/catalog/blob/main/task/kaniko/0.6/kaniko.yaml#L32
2. Replace Line #32 to: `gcr.io/kaniko-project/executor:v1.9.2@sha034f15e6fe235490e64a4173d02d0a41f61382450c314fffed9b8ca96dff66b2`
3. Run the task

# Additional Info
The reason I'm trying to use the latest is because the default version `v1.5.1` is having some security vulnerabilities that I would like to get fixed.

**Comment by vdemeester** [comment]
There was an issue on the pipeline side (https://github.com/tektoncd/pipeline/issues/6257) that got fixed recently. The fix should be available in 0.47.0.
