### ISSUE TITLE
Build Fails for the Node version 14.21.3 

### ISSUE THREAD

**Issue by mrcodecloud** [tektoncd/catalog#1177]
# Expected Behavior
Building Image successfully 

# Actual Behavior
Fails to build image when the base image is node:14.21.3 

# Steps to Reproduce the Problem

1. Create a Dockerfile with the node:14.21.3 as base image

# Additional Info
We are getting following error in the build step when building using tekton, where it's working fine with the Buildconfig on OKD dev namespace, so the Dockerfile is fine.

E0706 13:26:55.936259      16 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[36mINFO[0m[0000] Resolved base name node:14.21.3 to builder   
[36mINFO[0m[0000] Using dockerignore file: /workspace/source/.dockerignore 
[36mINFO[0m[0000] Retrieving image manifest 0                  
error building image: could not parse reference: 0
STEP-WRITE-URL

**Comment by AlanGreene** [comment]
Hi @mrcodecloud, can you share more details about the issue you're seeing? Which catalog task are you using? Can you share how you're using it?

**Comment by mrcodecloud** [comment]
It was due to an issue in the Dockerfile, Some lines were accidentally removed from Dockerfile
