### ISSUE TITLE
Tekton task "sonarqube-scanner" (v0.4) - gives failure

### ISSUE THREAD

**Issue by johan974** [tektoncd/catalog#1216]
# Expected Behavior
When running the task 'sonarqube-scanner/0.4' I get an error. I know that the overall settings are ok. 

# Actual Behavior
I got a failure: 
Error: dl failure on line 631
Error: failed /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so, because Error loading shared library /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so: Exec format error

# Steps to Reproduce the Problem

This is the pipeline I fit the taskref in: 

    - name: code-analysis
      taskRef:
        name: sonarqube-scanner
      runAfter:
        - maven
      params:
        - name: SONAR_HOST_URL
          value: http://localhost:9000
        - name: SONAR_PROJECT_KEY
          value: quotes
      workspaces:
        - name: source
          workspace: source-workspace
        - name: sonar-settings
          workspace: sonar-settings

The source code is JDK17. 

Maybe the maven did not run, but I guess that is not important when running without code coverage.

**Comment by vdemeester** [comment]
@johan974 thanks for the issue. Do you know which architecture you are running your Task/Pipeline ? The error `Exec format error` seems like it runs on an architecture that is not supported (aka the image is only for x86_64 and the arch it executes onto is aarch64, for example).

**Comment by johan974** [comment]
I am running (in this case) in a Windows 10 / DockerDesktop environment. 
I think the issue has to do with the older docker image. I will try a newer one tomorrow.

**Comment by johan974** [comment]
Above setting is correct. 

    - name: code-analysis
      taskRef:
        name: sonarqube-scanner
      runAfter:
        - maven
      params:
        - name: SONAR_HOST_URL
          value: http://localhost:9000
        - name: SONAR_PROJECT_KEY
          value: quotes
        - name: SONAR_SCANNER_IMAGE
          value: sonarsource/sonar-scanner-cli:5
      workspaces:
        - name: source
          workspace: source-workspace
        - name: sonar-settings
          workspace: sonar-settings
