### ISSUE TITLE
Tekton task "git-clone": cannot use git-clone with localhost repo

### ISSUE THREAD

**Issue by johan974** [tektoncd/catalog#1221]
# Expected Behavior
My pipeline first accessed a repo on github.com.
 
For testing purposes, I added a Gogs repo locally. 

When connecting to this repo "http://localhost:3000/gituser/quotes.git" I get an error that the connection is refused. I can just access it normally via the browser. Also from my IDE. 

# Actual Behavior
Just connecting to the repo, I get this error: 

+ git config --global --add [safe.directory](http://safe.directory/) /workspace/output
+ /ko-app/git-init '-url=http://localhost:3000/gituser/quotes.git' '-revision=master' '-refspec=' '-path=/workspace/output/' '-sslVerify=false' '-submodules=true' '-depth=1' '-sparseCheckoutDirectories='
{"level":"warn","ts":1700767716.1000483,"caller":"git/git.go:269","msg":"SSH credentials have been provided but the URL(\"[http://localhost:3000/gituser/quotes.git\](http://localhost:3000/gituser/quotes.git/)") is not a valid SSH URL. This warning can be safely ignored if the URL is for a public repo or you are using basic auth"}
{"level":"error","ts":1700767716.3557546,"caller":"git/git.go:53","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force master]: exit status 128\nfatal: unable to access 'http://localhost:3000/gituser/quotes.git/': Failed to connect to localhost port 3000 after 0 ms: Connection refused\n","stacktrace":"[github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:53\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:156\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:250](http://github.com/tektoncd/pipeline/pkg/git.run/n/tgithub.com/tektoncd/pipeline/pkg/git/git.go:53/ngithub.com/tektoncd/pipeline/pkg/git.Fetch/n/tgithub.com/tektoncd/pipeline/pkg/git/git.go:156/nmain.main/n/tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53/nruntime.main/n/truntime/proc.go:250)"}
{"level":"fatal","ts":1700767716.3558109,"caller":"git-init/main.go:54","msg":"Error fetching git repository: failed to fetch [master]: exit status 128","stacktrace":"main.main\n\[tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:250](http://tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54/nruntime.main/n/truntime/proc.go:250)"}

# Steps to Reproduce the Problem

This is the Pipeline: 

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-with-sonar
spec:
  params:
    - name: SOURCE_URL
      type: string
      description: A git repo url where the source code resides.
    - name: SOURCE_REVISION
      description: The branch, tag or SHA to checkout.
      default: ""
    - name: TARGET_VERSION
      description: The target build revision of the Docker image
      default: ""
  workspaces:
    - name: source-workspace
    - name: maven-settings
    - name: config-source
    - name: sonar-settings
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: url
          value: "$(params.SOURCE_URL)"
        - name: revision
          value: "$(params.SOURCE_REVISION)"
        - name: subdirectory
          value: ""
        - name: sslVerify
          value: false
        - name: deleteExisting
          value: "true"
        - name: verbose
          value: true

**Comment by vdemeester** [comment]
@johan974 this is to be expected. `localhost` from a tekton task (or any Kubernetes pod for that matter) is the container itself, not your laptop. This means when using `localhost:3000`, `git` will look for an http server on port 3000 in the running container which is not there. 

For the Task to be able to connect to the gogs instance, assuming you run in kind, you would need to run `gogs` in kind as well *and* make it a service, in the same namespace your task runs, for it to pull available. And you would need to clone using a url like `http://{gogs-service-name}` instead of `localhost:3000`.

**Comment by johan974** [comment]
Thank you so much for the good explanation! Yes, I should have known ... growing from DockerSwarm into an enthusiastic Kubernetes fan! I solved it for testing purposes via a better addressing of the Gogs (local) server: serviceX.namespaceB.svc.cluster.local:3000.
