### ISSUE TITLE
Remove `--no-cache` in buildah

### ISSUE THREAD

**Issue by jimmyjones2** [tektoncd/catalog#1229]
In #265 the option `--no-cache` was added unconditionally as a buildah arguments, due to limitations of buildah at the time. Buildah has changed in the meantime, and this option no longer makes the build faster as layers are not cached by default (`--layers` is defaulted to false if not specified). I've verified this with a simple Dockerfile:

`buildah bud` - consistently 9s
`buildah bud --no-cache` - consistently 9s
`buildah bud --layers` - 39s first run, subsequent 1s

Therefore `--no-cache` is no longer required. Having this option present, prevents the user from taking advantage of buildah's distributed cache (by setting `--cache-to` and `--cache-from` in `BUILD_EXTRA_ARGS`)

@holly-cummins @vdemeester

**Comment by kubasikus** [comment]
I wanted to enable the distributed cache and ran into this problem. I had to create a custom Tekton Task to deal with this hardcoded option. Removing it would be great :)
