### ISSUE TITLE
git-init base-image/dockerfile was deprecated/removed, but is still in use

### ISSUE THREAD

**Issue by mathew-fleisch** [tektoncd/catalog#1242]
It looks like last year @lbernick deprecated the git-init container from being released here:
https://github.com/tektoncd/pipeline/commit/8541ed1d1173424e9b03684223b553da16be938f

However, I still see it referenced in the latest git-clone task here:
https://github.com/tektoncd/catalog/blob/5168415df3c4e851b81a09bd97138b1d5278307c/task/git-clone/0.9/git-clone.yaml#L105

I would like to build my own version of this image, but cannot find the dockerfile that originally created. Can anyone help me understand how this container is being maintained/or-not and how I might build my own version to not use a public container.

**Comment by emirot** [comment]
I looked into that at some point and it is not clear to me as well.

What I was able to find it from an old release 
- https://github.com/tektoncd/pipeline/blob/v0.25.0/images/git-init/Dockerfile
- and there is a wrapper around it https://github.com/tektoncd/pipeline/blob/v0.25.0/cmd/git-init/main.go 

So I believe (not 100% sure though) this is what you are looking for, as I m not familiar with how the two were put together maybe kodata ? 

you can see that 
```
docker run -it  --entrypoint=bash gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
cat /proc/version
Linux version 6.4.16-linuxkit (root@buildkitsandbox) (gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, GNU ld (GNU Binutils) 2.40) #1 SMP PREEMPT Sat Sep 23 13:36:48 UTC 2023
```

So I have reasons to think that the two files above main.go and the dockerfile were assemble to create the image.

@mathew-fleisch

**Comment by vdemeester** [comment]
@mathew-fleisch @emirot the "code" is *maintained" here : https://github.com/tektoncd-catalog/git-clone/tree/main/image/git-init. There is no `Dockerfile` because we use `ko` to build the image (`ko publish ./image/git-init`).

**Comment by mathew-fleisch** [comment]
aha! thanks for that!
