### ISSUE TITLE
bazel.yaml from the tutorial

### ISSUE THREAD

**Issue by bugsbunnyshah** [tektoncd/catalog#131]
# Additional Info
I am looking for the bazel.yaml file being referenced in the tutorial under the the following command:

$ kubectl apply -f bazel.yaml
task.tekton.dev/bazel created

I am trying to work with the following nodejs project:

git clone -b v1 https://github.com/docker-training/node-bulletin-board

Thanks
Sohil

**Comment by vdemeester** [comment]
@bugsbunnyshah right, we need to update the README, the `bazel` task is not present for some reason (cc @ImJasonH).

/kind documentation

**Comment by bugsbunnyshah** [comment]
Thank you. That would save me some time as I am looking to make steady progress with Kubernetes and tecktoncd. I must say you guys have built something really good at the alpha level.

Also, it gave me an opportunity to take a look at bazel. It is very nicely done as well.

Have a nice day
-Sohil

**Comment by MarckK** [comment]
I ran into this as well. 

It would be great to have a Bazel task. :)

**Comment by zhouhaibing089** [comment]
> the bazel task is not present for some reason 

Interesting, curious on what was the reason?

**Comment by so0k** [comment]
@zhouhaibing089 - https://github.com/tektoncd/catalog/pull/21

**Comment by zhouhaibing089** [comment]
Thanks @so0k . That's pretty helpful.

Replied in https://github.com/tektoncd/catalog/pull/21#issuecomment-735419546
