### ISSUE TITLE
Problems getting the cloud native buildpacks example to run because of missing builder image

### ISSUE THREAD

**Issue by kinkerl** [tektoncd/catalog#151]
# Expected Behavior

Follow the example in the `buildpacks`directory and get it to run. 

# Actual Behavior

Looks like the used builder docker image does not exist anymore. It is referenced in the task run as "gcr.io/cncf-buildpacks-ci/tekton-cnb-test:bionic" but it looks like it got removed. Is there a new home for it somewhere?

# Steps to Reproduce the Problem

1. docker pull gcr.io/cncf-buildpacks-ci/tekton-cnb-test:bionic

# Additional Info

**Comment by sbose78** [comment]
So, this works:
`docker pull cloudfoundry/cnb:bionic`

**Comment by ameyer-pivotal** [comment]
@kinkerl That builder was just an example, not a real builder. We're updating this task to conform to a later builder. Try out the task in https://github.com/tektoncd/catalog/pull/175.

**Comment by jromero** [comment]
@vdemeester This should be resolved.

@kinkerl let us know if that is incorrect.

**Comment by vdemeester** [comment]
Ah I see #175 refered this issue :angel: 
/close
