### ISSUE TITLE
Buildpacks Task should support the platform directory

### ISSUE THREAD

**Issue by mattysweeps** [tektoncd/catalog#160]
# Expected Behavior

User variable are stored as files in `/$platform_dir/env/` so buildpacks can utilize them.

# Actual Behavior

`$platform_dir` is never set, so the lifecycle binaries choose the default value `/platform`. However, `/platform` is not a configurable volume mount.

# Additional Info

See https://github.com/buildpacks/spec/blob/master/buildpack.md#detectiona

**Comment by natalieparellano** [comment]
On discussing this with @zmackie we see a couple ways forward:

* Allow users to mount their own `/platform` or `/platform/env`
  * This is a bit cumbersome - users would need to construct the volume and write their own `/platform/env/MY_VAR` files
* Provide some mechanism to consume a list of variables and write files to disk. 
  * Prior art: kpack does it [here](https://github.com/pivotal/kpack/blob/019fd44d611a0b7fac469437f316596982954989/pkg/cnb/platform_env_vars_setup.go#L10:6); pack does it [here](https://github.com/buildpacks/pack/blob/eab3c1a11c84e39a7cd9f041e8e421def2f027c6/internal/builder/builder.go#L624)
  * We're not sure exactly how this would work. Presumably we'd need some sort of binary that could run as part of [prepare](https://github.com/tektoncd/catalog/blob/0ad08d92fa5f015bf9b719d2d91846f581f5ee79/buildpacks/buildpacks-v3.yaml#L40) or some other step in between prepare and detect. The question remains how we'd ship this binary - potentially we could make use of the upcoming [lifecycle image](https://github.com/buildpacks/lifecycle/issues/285). We'd also need a way to call the binary with the correct arguments - perhaps a new param `PLATFORM_ENV` in the TaskRun and Task.

We're not exactly sure how to proceed, welcome any inputs.

**Comment by natalieparellano** [comment]
We've submitted a PR (#302) that should go part of the way in addressing this use case. Our implementation requires the user to supply an appropriately formatted `/platform` directory with the desired `/platform/env/MY_VAR` files. 

This is cumbersome, but we are hoping that the work to implement [project.toml](https://github.com/buildpacks/rfcs/blob/master/text/0019-project-descriptor.md) will eventually provide a much easier user experience.
