### ISSUE TITLE
Buildpacks: bypass detect step

### ISSUE THREAD

**Issue by poy** [tektoncd/catalog#161]
# Expected Behavior
There should be a way for a user to set the desired buildpack and skip the detection work. I wouldn't expect the Tekton step as a whole to be skipped, however I would expect it to take in my input and make it a no-op.

The `pack` CLI has the option to do this when building images:

```
pack build --buildpack
```

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by dfreilich** [comment]
@poy I'm sorry that this slipped through the cracks! We definitely agree, though it is going to be a different process than `pack` uses. 

[This conversation](https://buildpacks.slack.com/archives/CSFE49VGR/p1594917693186400?thread_ts=1594912690.185400&cid=CSFE49VGR) on the Buildpacks slack notes: 
> --buildpack in pack is different from -buildpacks in the lifecycle. The latter only sets the buildpack directory and does not affect the buildpack detection order. To set the dectection order in tekton, you will need to write an order.toml file and pass it in with -order

We'll work on getting this through.

**Comment by dfreilich** [comment]
@poy when we looked into it a bit more, we had a bit of difficulty thinking of a use case for this. Users can create a special builder if they'd like that matches their applications, and that would prove to be easier and less likely to clog up the task. Is there a particular use case we're not addressing here that we could be?
