### ISSUE TITLE
Change Install Instructions to Use tkn Instead of kubectl

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/catalog#163]
The [install instructions](https://github.com/tektoncd/catalog/tree/master/gcloud#install-the-task) for tasks in this repository recommend the use of `kubectl apply` to create tasks. A big challenge as part of the CLI project has been trying to give users an experience with `tkn` that limits the use of switching back and forth between `tkn` and `kubectl`. As part of this effort, I think it would make sense to recommend `tkn task create -f` instead of `kubectl apply -f`. `tkn` will also eventually offer an `apply` subcommand, so we could wait for that as well before updating instructions. 

/kind documentation

**Comment by vdemeester** [comment]
We may also want to add some tests with `tkn` in there ? 
/cc @chmouel

**Comment by danielhelfand** [comment]
Going to close this as I think there is work to be done still for create/update approaches with `tkn`.
