### ISSUE TITLE
kaniko: image push on OpenShift fails - UNAUTHORIZED: authentication required

### ISSUE THREAD

**Issue by maheshwarishikha** [tektoncd/catalog#177]
# Expected Behavior
I am using Kaniko task for image build and push. Configured taskrun as suggested. But it fails with error:
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker-registry-default.xx.xxx.appdomain.cloud/tektonpipeline/imagename:latest": UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tektonpipeline/imagename Type:repository] map[Action:push Class: Name:tektonpipeline/imageapp Type:repository]]

Some permission issue. 
I have created a service account and given its reference in Pipelinerun. Later I found that I do not have secret.yaml. But not understanding that how to fill-in detailss for secret.

apiVersion: v1
kind: Secret
metadata:
  name: pipelinesa-token-7vnnc
annotations:
   tekton.dev/docker-0: ??? (in case of openshift - what it should be)
type: kubernetes.io/basic-auth
stringData:
      token: ??
      OR username and password is required?

In case of service account, we login to openshift using token. So not sure which username and password to use.
Kindly help.

**Comment by chmouel** [comment]
you need to give the serviceAccount the role to be able to push to the internal registry, ie : 

```
oc policy add-role-to-user system:image-builder system:serviceaccount:pushed:pusher
```

And just FYI  the openshift mailing list would probably be a better place for those kind of questions :  http://lists.openshift.redhat.com/openshiftmm/listinfo/users

**Comment by maheshwarishikha** [comment]
@chmouel, Thanks. 

This oc adm policy - did not work for me. 
I think...I need to find out a way to provide secret for service account.

**Comment by chmouel** [comment]
`kubectl edit sa thenameofthesa` and add it to the in the `secrets` sections i.e: 

there is quite a bit of documentation on the web about it that explains it further..

**Comment by maheshwarishikha** [comment]
Followed this - https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/  - created regcred and referred the same in serviceaccount.yaml

It worked for me. Hence closing the issue. Thanks.
