### ISSUE TITLE
Buildpack export step runs for a long time

### ISSUE THREAD

**Issue by anxinyf** [tektoncd/catalog#184]
# Expected Behavior
Export step runs quickly(succeed or failed).

# Actual Behavior
![image](https://user-images.githubusercontent.com/37263263/74609556-1e77db80-5126-11ea-86a4-05f41d5bdbbd.png)

I run buildpack with tekton( tekton/catalog/buildpacks). Every time export step runs for a long time, about 10 mins. So uncomfortable.

# Steps to Reproduce the Problem

1. With right to access docker repo and git repo
2. run buildpack-v3.yaml
3. run taskrun.yaml

The whole step is completed successfully ,but it takes a lot of time for  export step to complete.

# Additional Info
lifecycle version 0.5.0
I have a valid builder image.

**Comment by dfreilich** [comment]
@anxinyf Is this still an issue?

**Comment by anxinyf** [comment]
@dfreilich 
Oh, already solved in https://github.com/buildpacks/lifecycle/issues/262 :) 
Just the reason for the lifecycle version
