### ISSUE TITLE
Update buildpacks to Platform API 0.3

### ISSUE THREAD

**Issue by jromero** [tektoncd/catalog#194]
The [upcoming version of the lifecycle](https://github.com/buildpacks/lifecycle/milestone/9) is to include some changes to the platform API. This will require some modifications to the buildpacks task to be compatible with the latest version.

**Comment by natalieparellano** [comment]
@ekcasey do you think this task should be updated to use `creator`?
___
Notes:

Platform API 0.3 comes with the following changes:

* Added support for project-metadata.toml. ([#230](https://github.com/buildpacks/lifecycle/pull/230))
* Added support for /lifecycle/creator. ([#243](https://github.com/buildpacks/lifecycle/pull/243))
* Added support for -process-type flag. ([#260](https://github.com/buildpacks/lifecycle/pull/260))
* [Breaking] Removal of the -helpers flag. ([#259](https://github.com/buildpacks/lifecycle/pull/259))

**Comment by natalieparellano** [comment]
Currently, it seems that secrets are provided to every step in the lifecycle. E.g., 

* When I create a secret, a service account with that secret, and reference the service account according to [these docs](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-git)
* And I modify my buildpack's `bin/detect` and `bin/build` to `cat ~/.git-credentials`
* And I run the taskrun with a builder containing my modified buildpack
* Then I see the contents of `~/.git-credentials` printed to stdout
