### ISSUE TITLE
Docs: git-clone: provide information about git credentials/ssh key/config etc

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/catalog#229]
Would be good to provide some info in this doc about how/where to specify the git credentials (private key) etc when using this: I know that w/ the old PipelineResource its based on some special annotation on a secret... but its not clear what it would be going forward as this is now offered as a replacement in the beta.

https://github.com/tektoncd/catalog/tree/master/git

**Comment by sbwsg** [comment]
You're right - we should document this as part of git-clone.  The very quick answer is that the git-clone Task supports exactly the same auth mechanism as the git PipelineResource does.  So following instructions from auth.md should get credentials into the right places for both pipeline resources and tasks.

**Comment by 2020testuser** [comment]
Trying to understand as will be using git clone. I don't need runAsUser - root in the task yaml if I use ServiceAccount in the pipeline?
Could you please provide more details on the security side as planning to use jib gradle and want to make sure it works with the service account and user-root is not needed.

Thanks!
