### ISSUE TITLE
Task(s) to manage kubernets resources in a cluster

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/catalog#233]
# Feature description
In the context of MLOps, but most likely also beyond that, it's a common use case to create / update / delete kubernetes resources as part of a Tekton pipeline.

The proposal here is to have a task or set of tasks in the catalog that would define a standard way of doing that in Tekton, which a clear and re-usable interface.

Inputs would be:
1. The resource meta, including type, name (template), namespace, labels and annotations, and the spec which could be an arbitrary JSON/YAML, which we would have to define how it is conveyed to the task
1. The target cluster, which could be a `cluster` PipelineResource or a set of params
1. The operation to be performed - i.e. create, replace, delete

This would be about managing single resources, so it shall not support provisioning the content of a folder or a generic YAML with multiple resources.

This could be implemented as one generic tasks that takes rather generic inputs, which could be usable for all resources, but have a weak validation - or a set of tasks, one per resource type, at least for common resources, which could have more strict checks on input params.

**Comment by vdemeester** [comment]
@afrittoli should this issue take over https://github.com/tektoncd/catalog/issues/37 ? :upside_down_face:

**Comment by afrittoli** [comment]
> #37

Oh, I. missed that one :)

We, we could do that. I guess for deployments we might also have tasks that support provisioning a set of resources at once, so everything that is needed to deploy a service (including deployment, configmap, secrets, ingress etc).

**Comment by ckadner** [comment]
In order to streamline that implementation from a [KFP-Tekton compiler](https://github.com/kubeflow/kfp-tekton/issues/49) perspective, we would like to follow the precedence laid out by Argo's ResourceTemplate, and create a Tekton Task with the following parameters:

- `action`: `['get', 'create', 'apply', 'delete', 'replace', 'patch']` -- the action to perform to the resource
- `merge_strategy`: `['strategic', 'merge', 'json']` -- the strategy used to merge a patch, defaults to "strategic"
- `success_condition`: a label selector expression which describes the `success` condition
- `failure_condition`: a label selector expression which describes the `failure` condition
- `manifest`: the kubernetes manifest

**Comment by animeshsingh** [comment]
@vincent-pli @vdemeester @afrittoli this is a high priority requirement coming from our internal product teams. Would be good to know how can we get this prioritized? I have also discussed these with the OpenShift pipelines team, the relevance and importance of the work effort.

**Comment by vincent-pli** [comment]
Could we just use image with `kubectl` and use `workspace` to mount related yaml files to the task, then make path of the yaml file as parameter then define `create`, `delete` as args...

**Comment by ckadner** [comment]
We want to use the new "ResourceTask" via a `taskRef` in our pipelines and provide the manifest YAML as a `string` parameter without having to create files workspaces file mounts etc.

For implementing the task, I think a `kubectl` wrapper image would be okay. Especially from a maintenance point of view since anyone working with Kubernetes would be able to understand the commands, fix issues, try command locally, etc.

**Comment by ckadner** [comment]
A quick searching of DockerHub brings up this `kubectl` image that looks promising and has 10M+ pulls (Apache 2.0 license):
- https://hub.docker.com/r/bitnami/kubectl/

There are also a few recipes to cook up a custom `kubectl` image:
- https://itnext.io/portable-kubernetes-management-with-kubectl-in-docker-cb861a2c3c02

**Comment by vincent-pli** [comment]
@ckadner 
and this one:
https://github.com/tektoncd/catalog/blob/270c8330d3108dd44d97640a525f2e487ac7dbb7/knctl/knctl-deploy.yaml#L16

**Comment by Tomcli** [comment]
In Argo it was done in the controller since they already have [kubectl](https://github.com/argoproj/argo/blob/master/Dockerfile) binary in the controller image.
https://github.com/argoproj/argo/blob/master/workflow/executor/resource.go#L22-L76

**Comment by Tomcli** [comment]
After we create/delete the resource, we also need to return a status to tell whether this is up running/deleted.

**Comment by vincent-pli** [comment]
@Tomcli 
I think a `kubectl` wrapper could satisfy you with some extra work.
for example:

- Create a pod, stuck until the pod is running:  
   you need extra loop to watch the status of pod.
- Create a pod, stuck until the pod complete and make decision base on output of the pod:
  then you could mount the same pvc (from the `workspace`) to the new created pod...

**Comment by animeshsingh** [comment]
@vincent-pli is this something you want to take forward? Get this pushed in tekton, and we can leverage it as part of KFP?

**Comment by vincent-pli** [comment]
@animeshsingh 
OK, I think I can make pr for `kubectl` wrapped example but no loop monitoring as @Tomcli  mentioned.

**Comment by vincent-pli** [comment]
#237

**Comment by ckadner** [comment]
Thanks for your PR @vincent-pli. I just took a quick look, but I only saw one parameter `resource`. Ideally we would need 4 more as I described in my comment  above:

https://github.com/tektoncd/catalog/issues/233#issuecomment-602850205

- `action`: `['get', 'create', 'apply', 'delete', 'replace', 'patch']` -- the action to perform to the resource
- `merge_strategy`: `['strategic', 'merge', 'json']` -- the strategy used to merge a patch, defaults to "strategic"
- `success_condition`: a label selector expression which describes the `success` condition
- `failure_condition`: a label selector expression which describes the `failure` condition
- `manifest`: the kubernetes manifest

Assuming your parameter `resource` really is the `manifest`, could we add `action` even if initally it only supports default action `create` or `apply`?

**Comment by vincent-pli** [comment]
@ckadner 


Sorry for delay, involved in a tough project.
The function you mentioned is correct and needed for a complete kubernete resource hendler features, it's too complex to just with script and yml, I think it should be a pre-prepared image.

Whatever, I will dig into and check if i can found something.

**Comment by Tomcli** [comment]
Thanks @vincent-pli, maybe you can add you kubeclient task for this? We still have some edge cases for the results that we love to have support such as https://github.com/kubeflow/kfp-tekton/issues/94

**Comment by vincent-pli** [comment]
Thanks @Tomcli , I add some draft code to address your requirement, please check that:https://github.com/vincent-pli/kubectl-wrapper

**Comment by animeshsingh** [comment]
thanks folks - @vincent-pli great to see this coming in as a PR soon
