### ISSUE TITLE
Update kaniko when 0.20 is released

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/catalog#235]
This PR fixes kaniko on EKS publishing to ECR with Tekton: https://github.com/GoogleContainerTools/kaniko/pull/1146

Just wanted to open an issue to track that.

**Comment by vdemeester** [comment]
@mattmoor the catalog now tracks `latest` by default, so, it will pick up 0.20 when it's released (or you can force the image version through params)

**Comment by mattmoor** [comment]
sweet!
/close
