### ISSUE TITLE
Add proxy support to git resource

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/catalog#238]
# Expected Behavior

All functionality exposed by the `git-init` image should be available through the git task.

# Actual Behavior

https://github.com/tektoncd/pipeline/pull/2215 added support for proxies to the git PipelineResource but this hasn't been added to the git Task yet.

**Comment by sbwsg** [comment]
Fixed by https://github.com/tektoncd/catalog/pull/231 I think?
