### ISSUE TITLE
Add Option Resource support to OpenShift Client Task

### ISSUE THREAD

**Issue by kameshsampath** [tektoncd/catalog#239]
# Expected Behavior
Currently the OpenShift Client task does not have `input` resources.  Having input resources helps in applying manifests from the sources like here https://github.com/tektoncd/pipeline/blob/master/examples/v1alpha1/pipelineruns/demo-optional-resources.yaml#L68

# Actual Behavior
Unable to apply manifests from the input source  using openshift-client task

Try using openshift-client Task in any pipelinerun like 

```    - name: deploy-kubernetes-service
      taskRef:
        name: openshift-client
      runAfter:
        - build-java-app
      params:
        - name: ARGS
          value:
            - "apply"
            - "-f"
            - "/workspace/source/$(params.contextDir)/k8s/app.yaml"```

It will fail with error ` error: the path "/workspace/source/apps/greeter/java/springboot/k8s/app.yaml" does not exist`, even if you have a previous task which would have built the image from application sources

**Comment by kameshsampath** [comment]
@piyush-garg @nikhil-thomas  ^^

**Comment by srethira** [comment]
@kameshsampath I ran into same limitation while running tekton in openshift v3.11. Is this feature available now ?

**Comment by kameshsampath** [comment]
It is merged now in to Tekton Catalog


-Kamesh
________________________________
