### ISSUE TITLE
"git-clone" not found

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/catalog#267]
# Expected Behavior
No errors when the log for pipelinerun is checked.
# Actual Behavior
When I run the below command, I get an error.

tkn pipelinerun logs jib-gradle-test-pipeline-run
Pipeline tekton-test/jib-gradle-test-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "git-clone": task.tekton.dev "git-clone" not found
# Steps to Reproduce the Problem

1. Run the yaml files under /catalog/gradle using kubectl apply.
2. Run the yaml file under /catalog/git using kubectl apply.
3. Getting an error when I check the logs for the Pipelinerun.

# Additional Info
Using the latest version of tekton.

**Comment by sbwsg** [comment]
`kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/v1beta1/git/git-clone.yaml` should resolve this problem.

This is done in jib-gradle's pre-apply-task-hook.sh: https://github.com/tektoncd/catalog/blob/v1beta1/jib-gradle/tests/pre-apply-task-hook.sh

**Comment by test2016new** [comment]
Ohh, missed it. No wonder it didn't work. Thanks Much!

**Comment by sbwsg** [comment]
That function, `add_sidecar_registry` is part of [e2e-common.sh](https://github.com/tektoncd/catalog/blob/v1beta1/test/e2e-common.sh#L26-L33) and all it does is update the file pointed at by `TMPF` with an extra `spec.sidecars` entry for the registry docker image.  So it's a path to a file but I'm not sure what file to provide it.  @chmouel or @vdemeester might be able to give more info on its usage though.

I'm closing this issue as I think the `git-clone` question is resolved.
