### ISSUE TITLE
Build using gradle

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/catalog#268]
# Expected Behavior
Using company docker registry and gradle to do the build in Tekton works as expected.

# Actual Behavior
Using company docker registry and gradle to do the build , results in an error. Simply involving the build.gradle content as a script in Tekton task. 
# Steps to Reproduce the Problem

1.  Took a copy of  /catalog/gradle Task and modified it to include my build.gradle content that builds the Dockerfile.
2. Using Company's Docker Registry to dump the newly created docker image.

# Additional Info
Using the latest version of Tekton.
<img width="931" alt="build-task" src="https://user-images.githubusercontent.com/22502313/78846010-f727e700-79cf-11ea-9d0c-20339191d0fc.png">

**Comment by 2020testuser** [comment]
Sorry. My mistake. The docker mount path was incorrect. Took a while to figure it out. I used MAC's docker path in the mount volume instead of Ubuntu's path. The docker path was not the same. Closing this as this is not an issue.

**Comment by bobcatfish** [comment]
No problem at all! Glad you figured it out @2020testuser :D
