### ISSUE TITLE
Error running git

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/catalog#297]
# Expected Behavior
The git-clone.yaml in /git works great. When the task is rerun with 'deleteExisting param set to true' , the existing folders/files must get deleted without any errors.

# Actual Behavior
When the task is rerun with 'deleteExisting param set to true' , getting the below error.

 {"level":"error","ts":xxxxx,"caller":"git/git.go:41","msg":"Error running git [remote add origin https://xxx@github.com/<app>.git]: exit status 128\nfatal: **remote origin already exists.**\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:79\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:203"}
[fetch-repository : clone] {"level":"fatal","ts":xxxxx,"caller":"git-init/main.go:54","msg":"Error fetching git repository: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:203"}

# Steps to Reproduce the Problem

1.Use /git in tektoncd/catalog .
2. Modify the params for git repo, revision etc. and set the param - deleteExisting = true to delete the existing content
3. Rerun the git-clone.yaml and you will hit the above error.

Any information on how this issue can be fixed would be greatly helpful. Thanks!

**Comment by piyush-garg** [comment]
This should be fixed by #327 

/close
