### ISSUE TITLE
Setup integration testing for tasks and pipelines

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/catalog#3]
Maintainers should be able to safely make changes to tasks and pipelines that we don't fully understand. This will require contributors to include tests of some form with their submissions.

**Comment by dlorenc** [comment]
A note on auth from @ImJasonH:

`I had thought about it. That gets tricky when the Task requires auth to successfully push the image. It's the same reason the build-templates repo never included actual running builds... 😒`

**Comment by dlorenc** [comment]
Here's what I'm thinking for tests:

1. We have a directory full of PipelineResources that TaskRuns can make use of during execution.
2. At the start of a test run, we create a namespace then create all of these PipelineResources in it.
3. For each `Task` we want to test:
    1. Parse the `Task` and examine the `Inputs`.
    2. Check to make sure we have a PipelineResource that fits that type.
    3. Figure out what to put in the `Params` (can be a file checked in, use defaults, etc.)
    4. Create the TaskRun, bound to the Resources we select from our pool
    5. Wait for it to complete.

We can further enhance this by adding another way to validate the `TaskRun` actually worked (outputs were produced, side effects happened, etc.).

**Comment by dlorenc** [comment]
Plan is to add some no-op tests first, get the prow configuration hooked up so they're passing, then extend the tests to get full coverage.

**Comment by afrittoli** [comment]
> A note on auth from @ImJasonH:
> 
> `I had thought about it. That gets tricky when the Task requires auth to successfully push the image. It's the same reason the build-templates repo never included actual running builds... 😒`

Perhaps tests could stand up a registry in the test cluster and point the Task to it?

**Comment by afrittoli** [comment]
>     3. For each `Task` we want to test:
>        
>        1. Parse the `Task` and examine the `Inputs`.
>        2. Check to make sure we have a PipelineResource that fits that type.
If we to actually run the Tasks, it may be that the resource type is not enough to match.
Take for instance a task that deploys and helm chart, may have a git input resource that holds the helm chart, so a generic git resource won't work, it must be a git repo that holds an helm chart, but there's no semantic about this in the Task definition. So I think we'll need to be able to have Task specific settings for tests e.g. specify resource names to be used.

**Comment by vdemeester** [comment]
#105 should be part of this :angel:

**Comment by vdemeester** [comment]
I wonder if we should close this one as prow has already an integration test job that does the simplest possible test (aka applying it and validating it works). Adding more tests can be tracked in additional issues and pull-request.

/cc @dlorenc

**Comment by vdemeester** [comment]
especiall as we do have https://github.com/tektoncd/catalog/issues/102 :sweat_smile:
