### ISSUE TITLE
"Checking for forbidden licenses" CI errors

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/catalog#305]
# Expected Behavior

Our license check should work on all PRs.

# Actual Behavior

I've seen the following error in two PRs:

```
--------------------------------------
---- Checking that go code builds ----
--------------------------------------
-----------------------------------------
---- Checking for forbidden licenses ----
-----------------------------------------
2020/05/06 08:36:33 Error creating license classifier: cannot register licenses from archive: open /go/src/knative.dev/test-infra/vendor/github.com/google/licenseclassifier/licenses/forbidden_licenses.db: no such file or directory
============================
==== BUILD TESTS FAILED ====
============================
+ EXIT_VALUE=1
+ set +o xtrace
```

#273 (logs: https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_catalog/273/pull-tekton-catalog-build-tests/1257952319127949312/)

#301 (logs: https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_catalog/301/pull-tekton-catalog-build-tests/1258010200590258176/)

**Comment by sbwsg** [comment]
Now apparently happening in all new PRs?  #304 also experiencing the problem.

**Comment by sbwsg** [comment]
Looks like this has been resolved (at least https://github.com/tektoncd/catalog/pull/304 is now passing where before it was failing with the license error)

**Comment by vdemeester** [comment]
Let's close this for now then. If it comes back, let's re-open
/close

**Comment by sbwsg** [comment]
It looks like the license problem is reappearing with PRs against the v1alpha1 branch: https://github.com/tektoncd/catalog/pull/314

Should we not make PRs against v1alpha1?  I guess that would be a solution to this problem too.

**Comment by vdemeester** [comment]
@sbwsg hum, so in a gist I would say "yes, we should consider `v1alpha1` as read-only" :upside_down_face: (otherwise, we need to to a "plumbing bump" :stuck_out_tongue_closed_eyes:

**Comment by vinamra28** [comment]
It looks like the license problem is reappearing with PRs. For reference [367](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_catalog/367/pull-tekton-catalog-build-tests/1284506618976800770/)
```
--------------------------------------
---- Checking that go code builds ----
--------------------------------------
-----------------------------------------
---- Checking for forbidden licenses ----
-----------------------------------------
Error: cannot register licenses from archive: open /home/prow/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-20190926221455-842c0d70d702/licenses/licenses.db: no such file or directory
Usage:
  licenses check <package> [flags]

Flags:
  -h, --help   help for check

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --confidence_threshold float       Minimum confidence required in order to positively identify a license. (default 0.9)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
```
