### ISSUE TITLE
Merge v1beta1 in master (2020, 15th June)

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/catalog#306]
Now that [`v1alpha1`](https://github.com/tektoncd/catalog/tree/v1alpha1) has been created based on `master`, we should be able to merge `v1beta1` into `master` at some point.

**Comment by sbwsg** [comment]
I think this will make @wlynch very happy. Questions:

- Will this mean that `master` becomes the correct place to merge new Tasks?
- And will we get rid of `v1beta1` / make `master` the default branch again?
- Seems like we might have an ongoing sync problem then where `master` and `v1beta1` are similar but not quite the same?

**Comment by vdemeester** [comment]
>     * Will this mean that `master` becomes the correct place to merge new Tasks?

After the merge yes. 

>     * And will we get rid of `v1beta1` / make `master` the default branch again?

We'll "freeze" `v1beta1` branch for a while, but yes.

>     * Seems like we might have an ongoing sync problem then where `master` and `v1beta1` are similar but not quite the same?

Depends on what you mean by that, we will merge v1beta1 in master, so then, opened PR will need to change their `base` branch.

**Comment by sbwsg** [comment]
Gotcha, getting rid of v1beta1 answers my question about the sync problem.  Deleting v1beta1 will mean there's no sync problem to keep on top of.

**Comment by vdemeester** [comment]
it is done.
/close
