### ISSUE TITLE
How to clone a specific commit on a specific branch with git-clone?

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/catalog#320]
# Expected Behavior

That the typical behavior for a `git-clone` in a CI-server context is documented.

Typically: `clone branch X from repository Y`

For reproducability, I would also like to have: `clone commit Z in branch X from repository Y`
e.g. so that I can re-run a failed run (e.g. flaky test), without fetching newer commits (that belong to another run)

# Actual Behavior

The [main example](https://github.com/tektoncd/catalog/tree/v1beta1/git) shows how to clone _master_ branch for a specified _repository_ into a chosen directory. This is useful for _personal projects_ but not more than that.

The answer may be in the documentation, but not in an easy to understand way.

/kind question
/kind documentation

**Comment by sbwsg** [comment]
I've written up an example of checking out a specific commit here: https://github.com/tektoncd/catalog/pull/321/files#diff-66e881212302d7e2e9b8e114054b90b9
