### ISSUE TITLE
kaniko task should us --digest-file

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/catalog#324]
The kaniko task uses this block to extract digest as the task result:
https://github.com/tektoncd/catalog/blob/89d86e142d1ed24f2dc2ea89b1a4160c8940d657/kaniko/kaniko.yaml#L47-L59

This *looks* like it extracts the digest post-push, which is actually racy (what if the tag moves?), and unsuitable for establishing proper provenance. 😬 

So I dug a little and found that kaniko has a [`--digest-file`](https://github.com/GoogleContainerTools/kaniko/blob/master/README.md#--digest-file) flag, and that worked for me in the context I was playing with yesterday.

cc @ImJasonH @vdemeester @bobcatfish @dlorenc 

If I get the CLA nonsense sorted out soon, I can try to knock this off, but it should be trivial.

**Comment by pvlltvk** [comment]
/reopen
I want to reopen this issue because I prepared a PR which implements this functionality.
