### ISSUE TITLE
Generic gsutil Task

### ISSUE THREAD

**Issue by wlynch** [tektoncd/catalog#348]
Tracking issue for adding catalog task for a generic gsutil CLI task to perform any gsutil command.

The existing [gcs](https://github.com/tektoncd/catalog/tree/v1beta1/gcs) tasks will be a great starting point here.

/kind feature
/assign dorismeixing

**Comment by dibyom** [comment]
gsutil commands: https://cloud.google.com/storage/docs/gsutil

**Comment by wlynch** [comment]
Merged in https://github.com/tektoncd/catalog/pull/359
