### ISSUE TITLE
Packs

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/catalog#366]
This is kind of feature requirement question.

Could you please let me know how to extend from an existing pipeline(s) (multiple pipelines in different repos.) , override the base pipeline(s) , merge two pipelines , support inheritance etc. ?
Is this possible in tekton? If so, could you provide details. 

If this feature is not available, it would be useful to include this as would be very useful for complex applications.

Thanks!

**Comment by chmouel** [comment]
Not answering fully your question but you can always use `kustomize` with tekton yamltemplates for advanced usage https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#overview-of-kustomize

**Comment by marcusmaday** [comment]
I have also been toying with the idea of pipeline "packs".  It seems like it would be useful to be able to group a series of pipelines together and inherit/override in a similar fashion to how Jenkins X buildpacks work.  It would be especially useful if those packs could inherit and resolve tekton objects from many git repositories and merge and apply those to build the pipeline.  I think it would be awesome for the tekton project to have a generic solution for this concept that didn't add all of the other assumptions that Jenkins X does.  Is there anything in the works to try and solve this issue in the Tekton project?
