### ISSUE TITLE
Can't get git-clone-checking-out-a-branch.yaml example pipeline to run to completion

### ISSUE THREAD

**Issue by guyhoskinsibm** [tektoncd/catalog#376]
# Expected Behavior
git-clone-checking-out-a-branch.yaml runs checking out code and cat-ing the readme

# Actual Behavior
repo is cloned (fetch-repo) task runs.
the next stage does not start:
 - a pod named affinity-assistant-... is in CrashLoopBackOff.
- Events within the pod show "pod has unbound immediate PersistentVolumeClaims (repeated 2 times)"
- logs from pod show
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Can not modify /etc/nginx/conf.d/default.conf (read-only file system?), exiting
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2020/06/19 16:01:35 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2020/06/19 16:01:35 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

# Steps to Reproduce the Problem

1. oc apply -f git-clone-checking-out-a-branch.yaml
2. watch pipeline progress in openshift web console
3.

# Additional Info
tkn version:
Client version: 0.10.0
Pipeline version: v0.13.2

Triggers version: v0.4.0
running on an openshift 4.3.23 cluster

git-clone-checking-out-a-branch.yaml  apiVersion: tekton.dev/v1beta1

**Comment by sbwsg** [comment]
This looks possibly like a permissions error related to running the nginx affinity assistant as non-root user?  Can you confirm what the securityContext was on the affinity assistant pod and its containers?

@jlpettersson have you seen any errors like this before with the assistant?

**Comment by sbwsg** [comment]
(for reference, this is the example in questions: https://github.com/tektoncd/catalog/blob/master/git/examples/git-clone-checking-out-a-branch.yaml)

**Comment by guyhoskinsibm** [comment]
Thanks @sbwsg I have not set up any securityContext on the pod

**Comment by sbwsg** [comment]
It looks like you're using `openshift`, is that right? (I'm assuming based on use of `oc`)

I believe that openshift randomizes the user that a pod runs as.

**Comment by guyhoskinsibm** [comment]
@sbwsg yes I am using openshift - applying the security context has got the affinity-assistant up. Thank you!
I am still getting PVC errors. 3 pods are spun up affininity-assistant and two for the pipeline - one for each task. One of the task pods always seems to error with:
```
Error while attaching the device pv pvc-bb82... cannot be attached to the node 10.222.3.208. Error: PV pvc-bb82... is already attached to another node 10.222.3.194 and there are active pods [affinity-assistant-fb6f35c2e4-0 git-clone-checking-out-a-branch-fetch-repo-p4wqt-pod-4xnxg] using that
```
looks like there is contention on the pv - any help on this would be much appreciated

**Comment by jlpettersson** [comment]
Hm, I have not seen those errors before.
The Affinity Assistant can be [disabled](https://github.com/tektoncd/pipeline/blob/master/config/config-feature-flags.yaml#L32).

I am not really understanding what may cause problems here.
Is there any _events_ on the pod, when describing it? `kubectl describe pod <my-pod-name>`

I wounder if the _affinity_ declared in the `PipelineRun` may be in conflict with the Affinity Assistant?
Does it work better it the following part of the `PipelineRun` is removed?

```
  podTemplate:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "tekton.dev/pipelineRun"
              operator: In
              values:
              - git-clone-checking-out-a-branch
          topologyKey: kubernetes.io/hostname
```

I am not sure what the intent with it is. I was expecting that this will be overwritten when the Affinity Assistant.

>cannot be attached to the node 10.222.3.208. Error: PV pvc-bb82... is already attached to another node 10.222.3.194

Sounds like the same volume is being used on two different nodes here. Is there two `PipelineRun` that is using the same `PVC`? ...but that should not be a problem since the two `PipelineRun` can not have the same name. I don't understand what caused this.

**Comment by guyhoskinsibm** [comment]
With the `Affinity` block removed when the pipeline was run there were 5 pods spun up. One affinity.assistant and 4 pipeline pods. The Affinity assistant ran the whole time no issues. For the pipeline only one of the pods ran at any one time, the others were stuck initialising and had errors like this.
```
Unable to attach or mount volumes: unmounted volumes=[ws-7gfmz], unattached volumes=[tekton-internal-tools tekton-internal-downward tekton-internal-workspace tekton-internal-secret-volume-git-ssh-key-drtv9 tekton-internal-home tekton-internal-secret-volume-build-bot-dockercfg-5fqbb-x6k66 build-bot-token-5v9bg tekton-internal-results tekton-internal-scripts ws-7gfmz]: timed out waiting for the condition
```
```
MountVolume.SetUp failed for volume "pvc-42c15..." : mount command failed, status: Failure, reason: Error while mounting the volume &errors.errorString{s:"RWO check has failed. DevicePath /var/data/kubelet/plugins/kubernetes.io/flexvolume/ibm/ibmc-block/mounts/pvc-42c15b.. is already mounted on mountpath /var/data/kubelet/pods/418b0.../volumes/ibm~ibmc-block/pvc-42c15... "}
```
When the pod that was running had completed its task (I determined this from looking at the logs), if I deleted the pod that had been running, another pod was able to run. By repeating this I was able to get the pipeline to complete. Two of the pods did not seem to complete a task in the pipeline (I am not sure why they were running at all).

To me it seems that contention around the pvc is causing the pipeline to stall. I have no other pipelines running or pods running accessing the PVC.
Should the pods running in the pipeline be able to share a PVC? or should each pod, when completed its task delete itself? I think either would allow the pipeline to run to completion.

**Comment by jlpettersson** [comment]
>MountVolume.SetUp failed for volume "pvc-42c15..." : mount command failed, status: Failure, reason: Error while mounting the volume &errors.errorString{s:"RWO check has failed. DevicePath /var/data/kubelet/plugins/kubernetes.io/flexvolume/ibm/ibmc-block/mounts/pvc-42c15b.. is already mounted on mountpath /var/data/kubelet/pods/418b0.../volumes/ibm~ibmc-block/pvc-42c15... "}

From the above message, it sound like your storage type is not compatible with the Affinity Assisant or parallel tasks, since it try to mount the volume on different paths? for each pod. I think the Affinity Assistant need to be disabled for that kind of storage.

**Comment by guyhoskinsibm** [comment]
@jlpettersson @sbwsg thank you so much for your help! I have tracked the problem I was having down to there being two versions of tekton pipelines running in my cluster, under different namespaces - this was creating the PVC conflict (an the reason why there were more pods than tasks being run!)
I am happy for this issue to be closed as it was my error

**Comment by sbwsg** [comment]
Fascinating, great work figuring that out and thanks for reporting back!
