### ISSUE TITLE
Decide/Include Submission Guidelines

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/catalog#4]
- [x] What type of tasks/pipelines are appropriate for this catalog?
- [ ] What are the requirements to become an OWNER of this catalog?
- [ ] What are the requirements to become an OWNER of a specific item in the catalog?

**Comment by vdemeester** [comment]
> What are the requirements to become an OWNER of this catalog?
Aren't those the share with the rest of the project (see on [`community`](https://github.com/tektoncd/community/blob/master/process.md#requirements))

> What are the requirements to become an OWNER of a specific item in the catalog?
Should the initial submitter of the pull-request add itself as an owner (or a few people) ?
