### ISSUE TITLE
Cloudevent test not working

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/catalog#422]
Clouevent tests yaml given are not working in CI right now

We have skipped the test for now in #421 to make the CI green.

This issue is created to make the tests working later.

**Comment by piyush-garg** [comment]
cc @iancoffey

**Comment by iancoffey** [comment]
Added a commit in https://github.com/tektoncd/catalog/pull/396 that should fix this

**Comment by piyush-garg** [comment]
Fixed in #396
