### ISSUE TITLE
Passing multiple workspaces into a task.

### ISSUE THREAD

**Issue by felixtran39** [tektoncd/catalog#444]
# Description
I have a pipeline that uses the git-clone task to clone a repository to a workspace. I do this for two different workspaces. Next, I attempt to pass both workspaces into a task. When running this pipeline, I see that it gets stuck on the task that I pass both workspaces into. (This task works fine when only one of the two workspaces is passed in).

# Expected Behavior
Task finishes successfully.
# Actual Behavior
Task is stuck in "PENDING".

When looking in the pod, I see this.
```
message: containers with incomplete status: [place-tools]
reason: ContainersNotInitialized
status: "False"
type: Initialized
```

# Steps to Reproduce the Problem

1. Create a pipeline 1. git-clone into a workspace, 2. git-clone into another workspace, 3. pass both workspaces into a task.
2. Run the pipeline.
3. Look at the pipelinerun and the taskruns resulting from the run. (Stuck in "PENDING")

**Comment by vdemeester** [comment]
So, this is most likely due to the affinity assistant (see [here](https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md#specifying-workspace-order-in-a-pipeline-and-affinity-assistants)). Overall, in the task you can define as many `workspace` as you want, but at runtime, you should, ideally, use only one PVC (with subpath in the workspace definition) so that you don't get into an unschedulable state.

/cc @jlpettersson

**Comment by yuwenma** [comment]
@vdemeester Thanks Vincent! In our use case, we used the [git-clone catalog](https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1) to fetch the repos and our task has to use multiple repos. If it's not suggested to use more than one workspace, is that possible to extend the functionality of the git-clone catalog, so as it can fetch multiple repos to a customized path? 

More context: In a CI/CD workflow, it's not unusual to use a separate repo to store (hydrated) app configurations. To use tekton as the CI/CD framework, the task would then have to deal with multiple repositories. 
/cc @bobcatfish

**Comment by jlpettersson** [comment]
>More context: In a CI/CD workflow, it's not unusual to use a separate repo to store (hydrated) app configurations. To use tekton as the CI/CD framework, the task would then have to deal with multiple repositories.

@yuwenma I agree with this. I tried to reason about multiple repos in a CI/CD workflow in the end of this comment https://github.com/tektoncd/pipeline/issues/3440#issuecomment-733109584, maybe you agree?
