### ISSUE TITLE
Feature Request: Results support for GCS upload/download

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/catalog#450]
The GCS upload/download tasks should support Task results, to indicate what files were uploaded/downloaded.

This is a little tricky though - we support wildcard paths/etc. so the number of files uploaded/downloaded is dynamic. Results are static. We probably need to have a single "result" that contains a manifest of what was uploaded/downloaded.

Something like:

```
gs://$url $digest
gs://$url $digest
```

for every uploaded/downloaded file.

It's also tricky because this output isn't very easy to retrieve from the gsutil output. We have a couple options:

1. Write a go binary that does the upload natively, supporting recursion and rsync style uploads. This would be non-trivial, but could make it easier to add support for other storage backends.
1. Write a binary to wrap gsutil to parse the stdout. This is probably less work than 1, but string/stdout parsing isn't very robust.
1. Shell scripting to parse the output. Easiest and lowest maintenance, but ugly bash scripts :(

**Comment by sbwsg** [comment]
Given that there's effectively no limit to the total number of entries in the manifest (and therefore its potential size) I wonder if this might be a sound use case for the [optional workspace](https://github.com/tektoncd/pipeline/issues/2119) feature instead?  A user could opt to pass in a workspace to receive the manifest and the task could decide to only generate that manifest if the workspace is provided.
