### ISSUE TITLE
Reorganise openwhisk to conform with catalog re-org TEP

### ISSUE THREAD

**Issue by sthaha** [tektoncd/catalog#453]
Creating this issue so that we don't miss the follow up reorganisation of the openwhisk related tasks, conditions and pipelines. 

`---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<-`

@vdemeester @mrutkows Just noting that I am okay with merging the patch since the TEP is still in `proposed` but please be aware that the way it is currently organised doesn't [conform to proposal](https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md#organization) ([see example](https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md#example-of-a-resource-from-catalog))  and wouldn't show up in the Hub preview. 
This can be addressed in a separate patch of course.

I am also unsure about the `.tmpl` files. 

Since the pipeline is usable, I don't think we should bikeshed on it. However, we should discuss this further in our WG call. 

cc: @chmouel

_Originally posted by @sthaha in https://github.com/tektoncd/catalog/pull/375#issuecomment-664987708_

**Comment by mrutkows** [comment]
@sthaha Please assign to me... I already have another branch that conforms with the updates made to the TEP 9 days ago...
