### ISSUE TITLE
[Request] Have a task supporting the bash commands

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/catalog#46]
## Feature request

The goal of this request is  to have a task supporting the execution of multiple bash commands as we can by example do using CircleCI. See : https://github.com/snowdrop/component-operator-demo/blob/master/.circleci/config.yml#L26-L32 

Tekton currently proposes this approach: https://github.com/tektoncd/pipeline/blob/master/examples/taskruns/task-env.yaml
but we can't group the commands to be executed by a container as currently it is restricted to what the k8s container spec allows

A workaround is perhaps to mount the bash script to be executed OR to have a parser converting a multiline bash commands into x args

**Comment by AdityaGupta1** [comment]
A workaround that I use is:

```YAML
command: ["bash", "-c", "command 1 ; command 2"]
```

But it would be nice to have a proper way to do multiple commands at once.

**Comment by vdemeester** [comment]
@cmoulliard I think the related issue in pipeline is https://github.com/tektoncd/pipeline/pull/1432, and thus I feel we can close this one :angel:

**Comment by cmoulliard** [comment]
Yes.
