### ISSUE TITLE
docker-build test task is failing

### ISSUE THREAD

**Issue by chmouel** [tektoncd/catalog#481]
# Expected Behavior

No failure :) 

# Actual Behavior

The test are sometime failing : 

`FAILED: docker-build task has failed to comeback properly`

The main issue seems to be with this : 

```
+ docker build --no-cache -f ./Dockerfile -t localhost:5000/nocode .
unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory
```

# Steps to Reproduce the Problem

1. Check the log [here](https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_catalog/479/pull-tekton-catalog-integration-tests/1292831095561129984/build-log.txt) from this [issue](https://github.com/tektoncd/catalog/pull/479#issuecomment-671397322)
2.
3.

# Additional Info

**Comment by chmouel** [comment]
cc @popcor255 @PuneetPunamiya @ImJasonH @vdemeester 

(people in the owners file for docker-build task)

it is breaking the catalog CI fyi,

**Comment by ImJasonH** [comment]
This is unexpected, since the Task's sidecar shouldn't report as ready until the certs are generated and available: https://github.com/tektoncd/catalog/blob/cb2b319b20b99bf48fd7d636fbe35afb170976b3/task/docker-build/0.1/docker-build.yaml#L100-L103

**Comment by popcor255** [comment]
I can not reproduce the error. @chmouel :\

**Comment by vinamra28** [comment]
@popcor255 could you please clone https://github.com/tektoncd/catalog/pull/485 and then try reproducing the problem. For now I have renamed the `tests` dir to `samples-1`.

**Comment by chmouel** [comment]
This is weird, maybe there is some race going on, i can def reproduce it every time when running the test manually :

<details>
  <summary>Manual run output: </summary>
<pre>
         name: output
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
+ echo '--- Container Logs'
--- Container Logs
++ kubectl get pod -o name -n docker-build-0-1
+ for pod in $(kubectl get pod -o name -n ${tns})
+ kubectl logs --all-containers -n docker-build-0-1 pod/affinity-assistant-f5130924a6-0
Error from server (BadRequest): container "affinity-assistant" in pod "affinity-assistant-f5130924a6-0" is waiting to start: ContainerCreating
+ true
+ for pod in $(kubectl get pod -o name -n ${tns})
+ kubectl logs --all-containers -n docker-build-0-1 pod/docker-test-pipeline-run-docker-build-ckphn-pod-ws67h
+ docker build --no-cache -f ./Dockerfile -t localhost:5000/nocode .
unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory
2020/08/11 13:33:08 Skipping step because a previous step failed
2020/08/11 13:33:14 Exiting...
+ for pod in $(kubectl get pod -o name -n ${tns})
+ kubectl logs --all-containers -n docker-build-0-1 pod/docker-test-pipeline-run-fetch-repository-9nsnz-pod-9b4jw
+ CHECKOUT_DIR=/workspace/output/
+ '[[' true '==' true ]]
+ cleandir
+ '[[' -d /workspace/output/ ]]
+ rm -rf /workspace/output//lost+found
+ rm -rf '/workspace/output//.[!.]*'
+ rm -rf '/workspace/output//..?*'
+ test -z
+ test -z
+ test -z
+ /ko-app/git-init -url https://github.com/popcor255/nocode -revision master -refspec  -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1
{"level":"info","ts":1597152766.533512,"caller":"git/git.go:139","msg":"Successfully cloned https://github.com/popcor255/nocode @ ef1a65b2f8e9a0cbf15c24c03ff8d202620512c5 (grafted, HEAD, origin/master) in path /workspace/output/"}
{"level":"info","ts":1597152766.5688412,"caller":"git/git.go:180","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
+ cd /workspace/output/
+ git rev-parse HEAD
+ tr -d '\n'
+ RESULT_SHA=ef1a65b2f8e9a0cbf15c24c03ff8d202620512c5
+ EXIT_CODE=0
+ '[' 0 '!=' 0 ]
+ echo -n ef1a65b2f8e9a0cbf15c24c03ff8d202620512c5
+ exit 1
+ clean
+ rm -f /tmp/.mm.ZYnuZH
chmouel@TheBatman 🦇 .../catalog OS4/tknaac master
%
</pre>
</details>

Can you try getting the latest catalog/master and run this on yoru cluster and see if that reproduces for you ?

```bash
% ./test/run-test.sh docker-build 0.1
```

it seems only to show up randomly in CI

**Comment by piyush-garg** [comment]
It just happened in Ci for me

```
unable to retrieve container logs for docker://ef392ddf1e7d9f858c50d4aebbaf77fe24e0edb4fbd8455c5eabc4dbf7ffbff4+ for pod in $(kubectl get pod -o name -n ${tns})
+ kubectl logs --all-containers -n docker-build-0-1 pod/docker-test-pipeline-run-docker-build-pcqrz-pod-n6h28
+ docker build --no-cache -f ./Dockerfile -t localhost:5000/nocode .
unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory
2020/08/11 13:50:50 Skipping step because a previous step failed
time="2020-08-11T13:50:49.643974068Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.11.2 instance.id=cfa8d05d-3511-40c4-8a7c-d547472d67a9 service=registry version=v2.7.1 
time="2020-08-11T13:50:49.644166722Z" level=info msg="Starting upload purge in 51m0s" go.version=go1.11.2 instance.id=cfa8d05d-3511-40c4-8a7c-d547472d67a9 service=registry version=v2.7.1 
time="2020-08-11T13:50:49.644181322Z" level=info msg="redis not configured" go.version=go1.11.2 instance.id=cfa8d05d-3511-40c4-8a7c-d547472d67a9 service=registry version=v2.7.1 
time="2020-08-11T13:50:49.656257876Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.11.2 instance.id=cfa8d05d-3511-40c4-8a7c-d547472d67a9 service=registry version=v2.7.1 
time="2020-08-11T13:50:49.656498312Z" level=info msg="listening on [::]:5000" go.version=go1.11.2 instance.id=cfa8d05d-3511-40c4-8a7c-d547472d67a9 service=registry version=v2.7.1
```

**Comment by chmouel** [comment]
we are going to disable the test in CI until we figure it out...

**Comment by piyush-garg** [comment]
Raised PR https://github.com/tektoncd/catalog/pull/487 to disable in CI

**Comment by popcor255** [comment]
Hey @chmouel @piyush-garg @vinamra28. Thanks for the feedback! I did not how to recreate the error without your help. :brain: So, I did some debugging and I found something really interesting.

When I run the task on the new dev environment from this pr https://github.com/tektoncd/catalog/pull/482  (I would get the following):
```bash
error: a container name must be specified for pod docker-test-pipeline-run-docker-build-zrbgw-pod-gvbqv, choose one of: [step-docker-build step-docker-push sidecar-registry] or one of the init containers: [place-scripts working-dir-initializer place-tools]
```
When I run the task on my old dev environment (I would get the following):
```bash
error: a container name must be specified for pod docker-test-pipeline-run-docker-build-5fhts-pod-dmpmv, choose one of: [step-docker-build step-docker-push sidecar-server] or one of the init containers: [place-scripts working-dir-initializer place-tools]
```
:thinking: If you look closely at the containers **sidecar-server** is now **sidecar-registry**.
Looks like this new test script hijacked my sidecar.
Like @ImJasonH said the sidecar-server generates the cert.
However, this script gets rid of it. The new test script is produces a false-negative. If you look at all the tasks in the catalog this is the only one with a sidecar. Which would explain why it didn't effect anyone else.

**Comment by afrittoli** [comment]
@vdemeester FYI
@popcor255 would you mind proposing a fix to avoid overriding existing sidecars?

**Comment by popcor255** [comment]
I wrote a pr to fix this bug specifically. There is some discussion having a one shared local repo. #491 However, there is gonna need some discussion on image-name/tags. Cause, if it's not consistent throughout all tasks, test will break.
