### ISSUE TITLE
Broken link in pipeline/openwhisk/0.1 README

### ISSUE THREAD

**Issue by jacobhjkim** [tektoncd/catalog#484]
# Expected Behavior

This file should exist
[https://github.com/tektoncd/catalog/blob/master/pipeline/openwhisk/0.1/pipeline/pipeline-to-build-openwhisk-app.yaml](https://github.com/tektoncd/catalog/blob/master/pipeline/openwhisk/0.1/pipeline/pipeline-to-build-openwhisk-app.yaml)

# Actual Behavior

pipeline-to-build-openwhisk-app.yaml doesn't exist, but it is listed in [README](https://github.com/tektoncd/catalog/blob/master/pipeline/openwhisk/0.1/README.md#installing-pipeline-resources)

> The Pipeline is defined in the Kubernetes-style YAML file: [pipeline-to-build-openwhisk-app.yaml](https://github.com/tektoncd/catalog/blob/master/pipeline/openwhisk/0.1/pipeline/pipeline-to-build-openwhisk-app.yaml). It includes reference to the shared Workspace called "openwhisk-workspace" and all referenced PipelineResources and Tasks.

# Steps to Reproduce the Problem

N/A

# Additional Info

**Comment by popcor255** [comment]
@mrutkows Openwhisk.yaml is missing. It is included in the bash script but not included in the pr.

**Comment by piyush-garg** [comment]
@mrutkows Can you please take a look at this. Thanks

**Comment by mrutkows** [comment]
> @mrutkows Openwhisk.yaml is missing. It is included in the bash script but not included in the pr.
@piyush-garg 

Yes, openwhisk.yaml was a rename that was requested and was supposed to be fixed with this PR:
https://github.com/tektoncd/catalog/pull/457

But there was additional requests to change again where some of the dependent resource files lived in an evolving directory structure which required more discussion to resolve it seemed and my job assignment changed which derailed my ability to actively engage.

**Comment by vinamra28** [comment]
@mrutkows or probably you can open a new PR and fix this issue and keep that PR which will fix the directory structure and other review comments

**Comment by mrutkows** [comment]
> @mrutkows or probably you can open a new PR and fix this issue and keep that PR which will fix the directory structure and other review comments. This way or the way you suggested both are fine

I would prefer the approach I sugg. as this can solve the problem immediately ;)
