### ISSUE TITLE
Support sparse-checkout with git-clone

### ISSUE THREAD

**Issue by kameshsampath** [tektoncd/catalog#488]
Currently the git-clone task does not have ability to do https://git-scm.com/docs/git-sparse-checkout, where as part of my task I can checkout only set of directories from the Git repositories. 

Advantage of this approach will help :

-  Tasks using the `CONTEXT_DIR` or `CONEXT` can use sparse checkout mode to clone only required the directories
-  When using nested repo it helps the to restrict the size of clone and required repositories.

https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/ ( this works only with Git > 2.25)

https://briancoyner.github.io/articles/2013-06-05-git-sparse-checkout/ ( pre 2.25 versions)

@chmouel  thoughts?

**Comment by a-rothwell** [comment]
I would like to work on this

**Comment by chmouel** [comment]
@a-rothwell  please feel free to take this if you still have some spare time!

**Comment by a-rothwell** [comment]
https://github.com/tektoncd/catalog/pull/638

**Comment by vinamra28** [comment]
closed in #638
/close
