### ISSUE TITLE
Decide on support "levels'

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/catalog#5]
Is everything in here at the same "level" of support? Do we need a "playground" area? Or maybe "stable" and "incubation", like helm/charts?

**Comment by siamaksade** [comment]
The Helm model is definitely useful. It gives space to expose more experimental tasks in this repo

**Comment by vdemeester** [comment]
Depending on where we are going with the [Pipeline Catalog Integration story](https://docs.google.com/document/d/1O8VHZ-7tNuuRjPNjPfdo8bD--WDrkcz-lbtJ3P8Wugs/edit#), the shape of the catalog might be *imposed*.

The helm catalog used folders: `stable` and `incubation`. We could go for the same sort of folder hierarchy :

- New task are added in incubation
- We can have different group of OWNERS for `stable` and `incubation` (with a larger number in `incubation`)

Questions would then be how do we decide when to promote `Task` from `incubation` to `stable` ?

**Comment by bobcatfish** [comment]
The catalog organization proposal (soon to be implementable?) addresses this: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md#support-tiers
