### ISSUE TITLE
Git clone Pipeline crashes 

### ISSUE THREAD

**Issue by abudavis** [tektoncd/catalog#505]
I am trying to run this Pipeline :https://github.com/tektoncd/catalog/blob/v1beta1/git/examples/using-git-clone-result.yaml
When I create the Pipeline using OpenShift GUI, I get the following error (Component Trace & Stack trace) below:

TypeError

```
Description:
undefined is not an object (evaluating 't.taskRef.kind')
```

```
in f
    in foreignObject
    in l
    in l
    in g
    in l
    in l
    in g
    in o
    in l
    in l
    in g
    in l
    in l
    in g
    in l
    in Unknown
    in svg
    in div
    in Unknown
    in Measure
    in l
    in div
    in Unknown
    in div
    in Unknown
    in div
    in Unknown
    in div
    in Unknown
    in t
    in t
    in div
    in Data
    in StatusBox
    in div
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in w
    in Unknown
    in w
    in Unknown
    in s
    in DetailsPage
    in Unknown
    in c
    in Unknown
    in w
    in t
    in t
    in div
    in div
    in section
    in d
    in Unknown
    in w
    in w
    in div
    in div
    in f
    in p
    in div
    in p
    in NotificationDrawer
    in Unknown
    in w
    in main
    in div
    in b
    in component
    in t
    in t
    in t
    in t
```

```
f@https://console-openshift-console.apps.test.jyy.company.com/static/pipeline-builder-page-chunk-a97d9330149982000d7c.min.js:1:145080
Fo@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:55580
Ks@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:98505
Bs@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:84252
Ns@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:81279
Ns@[native code]
Ds@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:79851
Ds@[native code]
https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:42002
https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:144:4121
di@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:41949
pi@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:41884
Is@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:136:80179
notify@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:23:76043
https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:23:75618
https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:65:2444
[native code]
https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:23:75693
[native code]
v@https://console-openshift-console.apps.test.jyy.company.com/static/vendors~main-chunk-e66fbb6cf750ddd6b9ef.min.js:17:122393
promiseReactionJob@[native code]
```

**Comment by piyush-garg** [comment]
@abudavis Did you create the task also before that?

**Comment by abudavis** [comment]
No, because I assumed git-clone is a cluster task? Or may be it needs to be identified as a "cluster task" in the pipeline?

**Comment by piyush-garg** [comment]
@abudavis 

Can you please then try adding Kind also here https://github.com/tektoncd/catalog/blob/v1beta1/git/examples/using-git-clone-result.yaml#L29

`kind: ClusterTask`

**Comment by abudavis** [comment]
The reported issue seems to be because the service account was missing in the PipelineRun, when "serviceAccountName: pipeline" is added, it works.

Now coming to the "ClusterTask" called "git-clone", this also worked provided the service account is specified as above, otherwise sometime get the reported error OR the pipeline runs endlessly with a red exclamation on the task.

Do you know if there is a cluster task for git-clone that allows pulling from multiple git repos in a control loop?

**Comment by piyush-garg** [comment]
Yaa adding pipeline is specific to `OpenShift Pipelines` glad it worked for you.

Regarding pulling multiple repos, I think you can reference the same task multiple times in pipelines and can provide the respective URL. I guess all the repos will be cloned in the same workspace.

**Comment by abudavis** [comment]
Thanks again.
By multiple git repos, I meant something like this wherein repo names are passed as a parameter (which can be 3, 30, etc) and one could loop through it for more actions.

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: picalc-pr-
spec:
  pipelineRef:
    name: clonegit-pipeline
  params:
    - name: gitUrl
      value: https://github.com/repo1.git, https://github.com/repo2.git, https://github.com/repo3.git
    - name: gitRevision
      value: beta-update
  serviceAccountName: pipeline
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: picalc-source-pvc
```

**Comment by piyush-garg** [comment]
This is something not available in the catalog, you can modify the task according to your use case

**Comment by abudavis** [comment]
Thanks again.
When using the git-clone cluster task, is there anyway to tell it to clone to a folder by the name of the repo its cloned from? I did see a "subdirectory" param, but rather than setting "subdirectory" to name of the repo, can this be done automatically as part of the git clone?

**Comment by piyush-garg** [comment]
Hi @abudavis 

Here is the git-clone task https://github.com/tektoncd/catalog/blob/v1beta1/git/git-clone.yaml which is designed considering most of the use cases/scenarios. If you have any specific use-case, you can modify accordingly and use. If there is something which can be a common case, feel free to raise a PR/issue. Thanks

**Comment by piyush-garg** [comment]
I will close this issue as it has been resolved.

/close
