### ISSUE TITLE
buildpacks task should support platform API 0.4

### ISSUE THREAD

**Issue by natalieparellano** [tektoncd/catalog#525]
# Expected Behavior

Buildpacks task should support buildpacks platform API 0.4

# Actual Behavior

It currently supports platform API 0.3

# Additional Info

This may be as simple as changing this line (and the equivalent one in buildpacks-phases): https://github.com/tektoncd/catalog/blob/b50f4d0e930cc0e187c166a050bae77b96a87c15/task/buildpacks/0.1/buildpacks.yaml#L64 from `0.3` -> `0.4`

We may wish to provide additional documentation around the changes that don't require the pipeline to be configured any differently, but might affect how users interact with the output: multi-call launcher, report.toml (including how to capture this if desired), removal of version from the BOM, error code interpretation. The [Platform 0.4](https://github.com/buildpacks/spec/milestone/1) milestone in buildpacks/spec has more detail about these changes.

**Comment by natalieparellano** [comment]
https://www.google.com/url?q=https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/%23customizing-the-termination-message&sa=D&ust=1601409562037000&usg=AFQjCNFUheyKCF8JDL-4ZhuDdjUqJrFopQ for capturing report.toml

**Comment by natalieparellano** [comment]
Started looking into this today, a couple of notes:

* the path for report.toml (`-report`) if not specified defaults to the working directory of the lifecycle which I thought was `/layers`, but I didn't see a report.toml there at the end of the build. Explicitly setting the path did produce a report. I am not sure where the report ends up in the default case.
* I tried setting `terminationMessagePath: /layers/report.toml` but I don't see the contents of the report in the logs even though the report is there (I tested it by adding a step at the end of the build to cat the contents of the file). Does `terminationMessagePath` not get populated on a successful run? [This test](https://github.com/kubernetes/kubernetes/blob/5b33feb9436874f97f87cf83f8566cebcf18df7b/test/e2e/common/runtime.go#L254) suggests that the message should be there, but probably I am missing something...
* I think `terminationMessagePath` is probably the right way to get the report (assuming we can get it to work) as the layers volume mount is currently not configurable

**Comment by natalieparellano** [comment]
/remove-lifecycle stale

I think this is something we still want to do. @jromero are you looking at it?

**Comment by jromero** [comment]
Resolved by https://github.com/buildpacks/tekton-integration/pull/16. To be released any day now. 😄

**Comment by jromero** [comment]
This is now done as part of our [latest release of `task/buildpacks`](https://github.com/tektoncd/catalog/tree/main/task/buildpacks/0.3#compatibility).

**Comment by natalieparellano** [comment]
> This is now done as part of our [latest release of `task/buildpacks`](https://github.com/tektoncd/catalog/tree/main/task/buildpacks/0.3#compatibility).

I think this issue can be closed!
