### ISSUE TITLE
Design a system for annotating Tasks with Tekton version support

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/catalog#53]
Some tasks in the catalog may only work with recent or old versions of Tekton. We should come up with a clear way to display this to catalog users.

**Comment by vdemeester** [comment]
@dlorenc this is kinda related to https://github.com/tektoncd/catalog/issues/96. Quoting the other issue.

> One solution would be to branch the catalog on a given cadence with the same major/minor version of tektoncd/pipeline – making, for example, the 0.6.0 catalog branch be compatible with tektoncd/pipeline 0.6.0 for sure.

I feel this would be the simplest way to support multiple version at a low cost.
