### ISSUE TITLE
Vulnerability scanning task

### ISSUE THREAD

**Issue by dibbles** [tektoncd/catalog#54]
It would be good to have an example vulnerability scanning task, as this is certainly something that will be widely used.... could look to using opensource scanning engines .... maybe something like anchore(?).

**Comment by garethr** [comment]
@dibbles I've created a set of Tekton Tasks for using Snyk to scan for vulnerabilities in https://github.com/garethr/snyk-tekton. These are still experimental but I'd love any feedback.

**Comment by dibbles** [comment]
Feeling guilty as not got any time to look at these in detail, but looks useful, would be good to also have container image vulnerability scanning.
