### ISSUE TITLE
Support grouping very closely related Tasks into a single folder / document

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/catalog#540]
# Expected Behavior

A Task author should be able to document closely related Tasks by organizing them together in a single directory or yaml file.

Here's the scenario:

1. Author writes three separate Tasks: setup, execute, teardown.
2. `setup` Task generates a token that `execute` and `teardown` both need to function.
3. The `execute` Task might need to run 1 or many times, each time with the same token.
4. The `teardown` Task might not need to be run at all.

Given the above constraints, Author wants to group the Tasks together. They' re primarily intended to work with each other but because they each have different usage characteristics they operate best as as individual Tasks.

# Actual Behavior

Right now the Catalog (and Hub) don't have explicit support for multiple Tasks in a single directory or file.  We also don't have any documented best practices around when to do this or not do this.

# Additional Info

Discussed during Catalog WG on Oct 1st 2020.  Suggested creating this issue to discuss ideas.  The two options I see right now:

1. Allow multiple Tasks to live alongside each other in a directory.  E.g. `task/foo/0.1/{setup,execute,teardown}.yaml`
2. Allow multiple Tasks to be placed into a single document that the hub understands. E.g:
```yaml
kind: Task
metadata:
  name: setup
# ...
---
kind: Task
metadata:
  name: execute
# ...
---
kind: Task
metadata:
  name: teardown
# ...
```

**Comment by sbwsg** [comment]
Further context: it looks like this remained an open question in [the catalog TEP](https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md#open-questions-1):

> ### Open questions
> Flat hierarchy or categories ? What about grouping resources, an example would be some Tasks, related to github. We may have a bunch of github related tasks (github-create-pullrequest, github-create-comment, github-update-check, …). Should those be grouped or "flat" ?

So it seems like there was not a final decision on this and it could be discussed further in a follow-up TEP?

**Comment by bobcatfish** [comment]
I also find this odd - maybe with "tags" the experience of viewing grouped Tasks in the UI would be enough?

Definitely think we could switch to a different layout if we can think of something better that supports this grouping.

**Comment by chmouel** [comment]
I do find it odd too, but when asked to @sthaha  it was mentioned that the reason being for avoiding name collusion and computable discovery : 

https://github.com/tektoncd/catalog/pull/559#discussion_r513197874

Which I am not sure how we can address this aside of having a list database (like dnf/yum/krew would have) and potentially bringing other issues.

**Comment by sthaha** [comment]
I agree with all the above. I find it quite limiting as well and for the time being we can leave Hub out of this discussion and focus on the constraints that a catalog should have. Hub like any other tools needs to understand what a catalog is an how it is organised to extract the information. 

 We can leave the constraint that the path of a resource should be computable from its kind, aside but I think we should think of a way to ensure there wouldn't be any kind/name collision in any catalog (not just in Tekton); i.e. when you search for `task/foobar` there should be only one resource (with one or more versions) in the catalog otherwise we can't develop tooling to search and install and it would be quite confusing to the user.

**Comment by sbwsg** [comment]
Given that we only have a single separate (`-`) for resource names and we currently allow top-level catalog entries in a resource directory to use `-` in their name, I don't actually think there's a way to prevent collisions against the existing format.  However, we could tackle the separator problem: we could introduce a new separator (`.`) but this is not compatible with `Pipelines` OR we could use `--`, which isn't currently in use in our catalog and therefore we can start linting against.

Something like this:

```
tasks/<group>/<subgroup>/<version>/<action>.yaml
```

And an associated naming format like this:

```
<group>--<subgroup>--<action>
```

So some examples:

```
tasks/my-service/modular/0.1/setup.yaml
tasks/my-service/modular/0.1/execute.yaml
tasks/my-service/modular/0.1/teardown.yaml
```

Become `my-service--modular--setup`, `my-service--modular--execute`, `my-service--modular--teardown`.

Visually this takes some getting used to.  Is there another approach to guarantee backwards-compatibility with the existing catalog entries?

**Comment by jromero** [comment]
There seems be some technical hurdles to overcome to achieve @sbwsg's proposal but I concur with the idea of introducing groups (aka namespacing) to better group tasks as opposed to simply having a single "name" field would be beneficial for discovery and organizational purposes.

**Comment by chmouel** [comment]
maybe having a manifest generated at merge time would solve the non human discoverability of the task? akin of how krew does it
