### ISSUE TITLE
kn task does not work on v0.5.2

### ISSUE THREAD

**Issue by zroubalik** [tektoncd/catalog#57]
# Expected Behavior
Knative service beeing deployed

# Actual Behavior
Not able to deploy simple helloworld Knative Service, seems like there's a problem with passing arguments to the kn service image. I used the example Task and TaskRun from https://github.com/tektoncd/catalog/tree/master/kn without any modifications, but got this error:
```
$ oc logs kn-create-pod-6a16e9    
$ 'service create' requires the service name given as single argument
```

This part is probably not correctly parsed by tekton:
https://github.com/tektoncd/catalog/blob/master/kn/kn-create.yaml#L20

I have tried to run the kn image directly with the same arguments and it is working as expected

# Additional Info
Running on OpenShift 4.1
(Kubernetes v1.13.4+3a25c9b)
Using Openshift-Pipelines Operator v 0.5.2

**Comment by vdemeester** [comment]
As of today, the catalog works on 0.7.0 and is not support for previous version. We want/need to enhance that and we are tracking those in https://github.com/tektoncd/catalog/issues/96

/close
