### ISSUE TITLE
Publish catalog to public OCI registry

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/catalog#577]
Hi,

with tekton pipelines now supporting Tasks & Pipelines from OCI registries, I think it would be really useful if the tasks in this repository are published to a public OCI registry. Is this planned?

There seems to be an open issue to also support git repos (https://github.com/tektoncd/pipeline/issues/2298) which would make this request obsolete but I´m not sure if or when this will be available. 

Thanks Fabian

**Comment by afrittoli** [comment]
I developed a [catalog task](https://github.com/tektoncd/catalog/tree/main/task/tekton-catalog-publish/0.1) for this - and the PR for nightly runs is [up](https://github.com/tektoncd/plumbing/pull/825). 

This will do a full run of the catalog, one bundle per task, and upload it nightly, with two tags, one the task version, and one the git sha. I already create and [example run](https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/publish-catalog-tekton-wgftg?pipelineTask=publish&step=publish), so the tasks are actually already there.

A second step could be to do this on PR merge, and update only the tasks affected by the PR, however this seemed to be less critical.
