### ISSUE TITLE
[Buildpacks] Warning "Tekton fails in step-image-digest-exporter with No index.json found"

### ISSUE THREAD

**Issue by SaschaSchwarze0** [tektoncd/catalog#616]
The sample task for buildpacks all define an output resource for the image, for example [here](https://github.com/tektoncd/catalog/blob/69179c92add7cdb30e776841fbbcd4c305b6843e/task/buildpacks/0.2/buildpacks.yaml#L53-L56):

```yaml
  resources:
    outputs:
      - name: image
        type: image
```

This leads to the logic described in [Surfacing the image digest built in a task](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#surfacing-the-image-digest-built-in-a-task) to apply. Tekton will try to find out the digest of the image at its default location, `/workspace/output/${resourceName}`, by checking the OCI image layout index.json. The code to extract the digest runs in the step-image-digest-exporter container after the Task's steps have finished.

The sample buildpacks task is not producing the index.json file and therefore causes the warning `Tekton fails in step-image-digest-exporter with No index.json found`.

# Expected Behavior

The sample task should either produce an index.json file so that the output resource can be used by Tekton, or does not define the output resource. (with a preference on the first choice ;-) )

# Actual Behavior

The output resource is defined but no index.json is produced leading to the image digest missing in the TaskRun's status and the warning in the logs.

# Steps to Reproduce the Problem

1. Use the [Buildpacks sample task with any suitable source code](https://github.com/tektoncd/catalog/blob/69179c92add7cdb30e776841fbbcd4c305b6843e/task/buildpacks/0.2/buildpacks.yaml)

# Additional Info

I slightly modified the task definition as a workaround:

1. I add `chown -R "$(params.USER_ID):$(params.GROUP_ID)" /workspace/output` to the prepare step
2. I add the `-report=/workspace/output/image/report.toml` argument to the `creator` call
3. I modified the `creator` step to not just run the `creator` but also this little script: `echo "{\"schemaVersion\":2,\"manifests\":[{\"mediaType\":\"application/vnd.docker.distribution.manifest.v2+json\",\"digest\":\"$(cat /workspace/output/image/report.toml | grep digest | tr -d ' \"' | sed s/digest=//)\"}]}" > /workspace/output/image/index.json`

This works, but while the first two things are okayish, the third item looks a little hacky. Maybe there is a better way to support this?

**Comment by jromero** [comment]
Resolved by https://github.com/tektoncd/catalog/pull/654

**Comment by jromero** [comment]
Hi @SaschaSchwarze0, we just released the [latest version of `task/buildpacks`](https://github.com/tektoncd/catalog/tree/main/task/buildpacks/0.3) which should negate this issue.

**Comment by SaschaSchwarze0** [comment]
Thanks @jromero
