### ISSUE TITLE
Do not run tests for removed tasks in PR

### ISSUE THREAD

**Issue by navidshaikh** [tektoncd/catalog#619]
# Expected Behavior
If a task is removed, do not run its e2e tests (or not try to create the removed task).

# Actual Behavior
While removing a task from catalog, e2e test script tries to run its e2e tests and fails the e2e run upon not finding the tests (or the task definition itself).
Looks like the `all_tests` should be populated from the changes in the PR.
https://github.com/tektoncd/catalog/blob/8d53c6ecf02777795c363e25d8eed8b2c2af23e7/test/e2e-tests.sh#L60

# Steps to Reproduce the Problem

1. Remove a task from catalog and raise the PR and notice the e2e tests fails complain failing to find the (removed) task definition.
2.
3.

# Additional Info
See the failure https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_catalog/618/pull-tekton-catalog-integration-tests/1351434107615186946/ for https://github.com/tektoncd/catalog/pull/618

**Comment by chmouel** [comment]
/cc @vinamra28 

he has been fixing all the ci run lately 🤗

**Comment by chmouel** [comment]
thanks @vinamra28 🙇🏽
