### ISSUE TITLE
ArgoCD task errors in 0.6.0 due to webhook failing validation of removed `containerTemplate` field

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/catalog#62]
# Expected Behavior

ArgoCD task applies successfully in 0.6.0.

# Actual Behavior

The ArgoCD task contains a `containerTemplate` field that has now been removed. The webhook now disallows unknown fields and so the ArgoCD task fails to apply.

# Steps to Reproduce the Problem

1. Run a cluster with tekton v0.6
2. Clone catalog
3. `kubectl apply -f ./argocd/argocd.yaml`

**Comment by vdemeester** [comment]
This is fixed in master
/close
