### ISSUE TITLE
Tekton tasks catalog in Artifact Hub

### ISSUE THREAD

**Issue by tegioz** [tektoncd/catalog#626]
Hi 👋 

We've just added support for Tekton tasks repositories to Artifact Hub. This will allow publishers listing the Tekton tasks available in their repositories in Artifact Hub.

The Tekton catalog repository [has been added](https://artifacthub.io/packages/search?page=1&repo=tekton-catalog-tasks) as an example. At the moment the publisher is the Artifact Hub organization, but it would be great if you could claim its ownership, so that the legit owner appears as the publisher. It's an easy and fully automated process documented [here](https://artifacthub.io/docs/topics/repositories/#ownership-claim).

Artifact Hub scans repositories periodically so any new tasks added or updated in the catalog repository will be listed automatically. We've also added support for some AH [specific annotations](https://artifacthub.io/docs/topics/annotations/tekton/) that can be used to improve users' experience in the UI.

If you notice something not working as expected or have any feedback please let us know 🙂 

Thank you very much!

CC: @caniszczyk

**Comment by vdemeester** [comment]
/kind feature
Nice, we should indeed investigate on this 😝

**Comment by nikhil-thomas** [comment]
@vdemeester @piyush-garg 
does our https://hub.tekton.dev/  lower the priority of this issue.
should we remove `lifecycle/rotten` or let the bot close this 

cc @chmouel @siamaksade
