### ISSUE TITLE
maven-test-pipeline-run uses a task named fetch-repository that doesn't exists

### ISSUE THREAD

**Issue by johnlongo** [tektoncd/catalog#627]
maven-test-pipeline-run uses a task named fetch-repository that doesn't exists.

<img width="967" alt="maven-test-pipeline-run" src="https://user-images.githubusercontent.com/23619505/106004018-c741f100-6080-11eb-9abf-c9cf30669906.png">

**Comment by chmouel** [comment]
You are trying to run the unit/functional pipelinerun test directly on your cluster, you are not supposed to use like this but can only take the test as an example...

In this case you probably would want to import the git-clone task into your namespace to be able to run it.

/kind question

**Comment by johnlongo** [comment]
ok, Thank you
