### ISSUE TITLE
Using sed rather than python has potential downsides

### ISSUE THREAD

**Issue by 06kellyjac** [tektoncd/catalog#678]
I've realized that the changes made in #665 could cause issues if it's not the first function ran against the file to inject the sidecar.
The method it's using is to add `sidecar: blah blah` in a place that's valid but the problem arises when there is already a `sidecar:` block either there already or a modification/injection was run before and already added it.

Sorry :facepalm: 

There are a couple options for resolving this:

* Add some bash to check if there's an existing `sidecar:` block and inject in there (or continue as now if it doesn't find a `sidecar:` block), with the downside of being a bit brittle
* Go back to using the python, with the downside of needing python as a dependency again
  * optionally could clean it up so it's more readable
  * or function-ize it to make it easier for other sidecar injection
* Use `yq-go` to manipulate the yaml easier and safer in scripts, with the downside of arguably just going from one dependency to another
  * Handles the complexity of yaml for you (similar to `jq`)
  * tends to be pretty readable
  * I personally prefer yq to python for this use-case
    * There is the matter of future complex scripting where python might be needed/preferred and then you end up with both python + yq required

**Comment by chmouel** [comment]
no worries, 

IMHO python is fine and should be pretty  much everywhere.

feel free to send a PR to revert this!
