### ISSUE TITLE
[git-clone]: Add sample for checking out pull request

### ISSUE THREAD

**Issue by zhouhaibing089** [tektoncd/catalog#694]
# Expected Behavior

In git-clone task, I would like to see an example showing how to clone a pull request. Specifically, I'm looking for two modes:

1. `refs/pull/${PULL_NUMBER}/head`: The pull request branch.
2. `refs/pull/${PULL_NUMBER}/merge`: The pull request merged with base.

# Actual Behavior

The existing examples are:

1. checkout branch
2. checkout commit
3. sparse checkout

**Comment by vinamra28** [comment]
cc @sbwsg

**Comment by sbwsg** [comment]
/kind feature

I don't think this is supported out-of-the-box with `git-clone` today so more than just examples we'd probably have to change the `script` that runs or the `git-init` binary too.  Marking this as a feature request.

For now you could use the [`git-cli`](https://github.com/tektoncd/catalog/tree/main/task/git-cli/0.1) task to perform the work needed to clone the PR or MR (gitlab).  The instructions for cloning a PR/MR for github/gitlab:

- Github: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally
- Gitlab: https://docs.gitlab.com/ee/user/project/merge_requests/reviewing_and_managing_merge_requests.html#checkout-merge-requests-locally-through-the-head-ref

**Comment by chmouel** [comment]
@sbwsg I think setting  something like this should work tho : 

```yaml
- name: repo_url
      value: https://github.com/chmouel/scratchpad/
    - name: revision
      value: FETCH_HEAD
    - name: refspec
      value: "refs/pull/172/head"
```

I have some issues with my pipeline atm so i cannot test (not sure why params.refspec doesn't get passed to the binary) but trying it with git-init directly would check out the PR directly.

**Comment by sbwsg** [comment]
> @sbwsg I think setting something like this should work tho :
> 
> ```yaml
> - name: repo_url
>   value: https://github.com/chmouel/scratchpad/
> - name: revision
>   value: FETCH_HEAD
> - name: refspec
>   value: "refs/pull/172/head"
> ```
> 
> I have some issues with my pipeline atm so i cannot test (not sure why params.refspec doesn't get passed to the binary) but trying it with git-init directly would check out the PR directly.

Oh, nice!  I never really understood what `refspec` was 😅 .  That's really cool, thanks for writing up the example!

**Comment by zhouhaibing089** [comment]
Thanks. I tried almost exactly the same - just don't know I should put `FETCH_HEAD` as revision. (I tried to use `HEAD`)
