### ISSUE TITLE
Idea: TekDoc tool, similar to godoc

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/catalog#7]
## Desired state

[godoc](https://godoc.org) hosts documentation for go projects. It finds these projects (scrapes them? not sure!) and looks for docstrings in [the required format](https://blog.golang.org/godoc-documenting-go-code) and uses that to generate (and i guess maintain? it must poll for changes) documentation, for example [this is some godoc generated docs for a function in tekton pipelines](https://godoc.org/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1#ApplyArrayReplacements, specifically [this function](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/pipeline/v1alpha1/substitution.go#L126).

What we would like is to be able to run an host a similar tool, maybe called TekDoc, that would show us for all the `Pipelines` and `Tasks` in tektoncd/catalog:

* The name of the Pipeline / Task
* Link to the source
* A description
* All parameters with descriptions + defaults
* All input/output resources with descriptions + defaults

### More requirements

(note we dont need to meet all of these right away, we can start with something super simple and iterate!)

* Other people have their own catalogs too, e.g. https://github.com/garethr/snyk-tekton. We should make it so this tool could also display those docs, both allowing for our tool to point at multiple catalogs, and making it so that ppl can run the tool themselves
* One day we might have more types in the catalog, like PipelineResources and [tekton triggers types](https://github.com/tektoncd/triggers) so we can't just assume `Pipelines` and `Tasks` only.
* We are making changes to Pipelines and Tasks at the moment, so we need to make sure that it wont be too hard to change the tool to deal with those changes
* We should allow for the tool to display versions of the Pipelines and Tasks

## Current state

1. At the moment all usage info is in READMEs that are submitted with the Pipelines and Tasks, e.g. this one https://github.com/tektoncd/catalog/tree/master/conftest#conftest
2. We have description fields for `params` but not for Pipelines and Tasks themselves, and not for the PipelineResources that they use

### Possible plan of attack

I tried to break it up into a few milestones, but some of it could happen in parallel!

[ Milestone 1: add the necessary info to the types ]

1. Add description field to Pipeline type
2. Add description field to Task type
3. Add description field to input & output resources in Task (https://github.com/tektoncd/pipeline/issues/1389)
4. Add description field to resources in Pipeline
5. Update Tasks in the catalog to use these fields (might have to wait for a Pipelines release to merge the change, our versioning policy for the catalog vs. pipelines is a bit adhoc at the moment, + @vdemeester )

Suggestion: assume markdown format for contents of descriptions

[ Milestone 2: create service and/or library that scrapes catalog info]

For this bit it would probably be good to understand how godoc scrapes & polls!

1. The tool/service/library should be able to be given a github repo, find the Tasks and Pipelines
2. The tool/service/library should from those Tasks and Pipelines be able to extract their docs

The idea is that the webserver in milestone 3 will use this, but we can develop and test it without needing to have the whole webserver completed.

[ Milestone 3: create webserver  ]

We can probably just pick any ol' webserver, but we'd want to make sure we can deploy and run it in a container. Would be great if the webserver we chose could automatically emit metrics to let us know if its up and running and if there are any errors.

1. The webserver should invoke the service, then display all the Tasks + Pipelines + their docs

## Additional info

* [about godoc](https://godoc.org/-/about)
* Note that we need to keep to [tekton's development principles](https://github.com/tektoncd/community/blob/master/standards.md#principles), e.g. the tool itself should be implemented with tests and docs as we go

## Original description

We could automatically generate interface documentation for the Tasks/Pipelines in this repository from the input and output parameters, and display this usage documentation nicely!

**Comment by bobcatfish** [comment]
oooo that sounds super sweet

**Comment by vdemeester** [comment]
that would be really good ! auto-generated on an url like https://catalog.tekton.dev :heart_eyes:

**Comment by bobcatfish** [comment]
Been talking with @ImJasonH and @wlynch and a great first step (ignore what I put in the description!) for this would be a command line tool that can generate some markdown from the existing description fields.

For example given these input params:

https://github.com/tektoncd/catalog/blob/1b3ceee11d6f1f177c1901007f46191a4e047d2c/buildpacks/buildpacks-v3.yaml#L6-L21

We would want to generate this markdown:

https://github.com/tektoncd/catalog/tree/master/buildpacks#parameters

![image](https://user-images.githubusercontent.com/432502/69663154-aed8df80-1053-11ea-9877-51d7dfe7f45f.png)

**Comment by bobcatfish** [comment]
@vdemeester now that we've got the hub, do you think this tool still makes sense?

**Comment by jromero** [comment]
I found this as I was looking for something like what @bobcatfish [mentioned](https://github.com/tektoncd/catalog/issues/7#issuecomment-558768019). AFAICT, Hub would simply display the README file for the task. Would it be possible to have the Hub provide the technicals (parameters, outputs, workspaces, etc)? The README could then be less structured data and instead be more helpful information like samples, community links, etc.

**Comment by vdemeester** [comment]
> I found this as I was looking for something like what @bobcatfish [mentioned](https://github.com/tektoncd/catalog/issues/7#issuecomment-558768019). AFAICT, Hub would simply display the README file for the task. Would it be possible to have the Hub provide the technicals (parameters, outputs, workspaces, etc)? The README could then be less structured data and instead be more helpful information like samples, community links, etc.

@jromero right, that would be something to bring to the @tektoncd/hub-maintainers team, but I tend to agree yes. It might even be on the hub roadmap 😉
