### ISSUE TITLE
Eliminate the usage of secretRef in Env

### ISSUE THREAD

**Issue by zhouhaibing089** [tektoncd/catalog#717]
# Expected Behavior

According to [CIS benchmarks][1].

> 5.4.1 Prefer using secrets as files over secrets as environment variables

# Actual Behavior

`env[*].secretKeyRef` is heavily used in this repository, [github-set-status][2] for example.

# Steps to Reproduce the Problem

N/A

# Additional Info

We internally tried to be compliant with CIS benchmark, so there is an internal admission which will block all pods creation if it has secretKeyRef in env. This introduces some trouble when we try to use some of the tasks here.

[1]: https://cloud.google.com/kubernetes-engine/docs/concepts/cis-benchmarks
[2]: https://github.com/tektoncd/catalog/blob/046fb8addbd49c5a8556417db8ce548e9de63040/task/github-set-status/0.2/github-set-status.yaml#L85-L90

**Comment by chmouel** [comment]
I agree, I think the only way we can make sure this happen is to add a rule into catlin https://github.com/chmouel/tektoncd-plumbing/blob/master/catlin/README.md

**Comment by zhouhaibing089** [comment]
Thanks for the link!

I'll see what I can do to address this issue - Hopefully it is just some YAML edits if the volumes can be substituted with params.

**Comment by zhouhaibing089** [comment]
I've proposed https://github.com/tektoncd/plumbing/pull/859 as the first step.

**Comment by zhouhaibing089** [comment]
I'm not sure what else is remaining. From what I can see, this can be closed considering:

1. New task specs are going to get warning.
2. Existing tasks shouldn't be modified.
