### ISSUE TITLE
Tekton plugins: should we support /usr/libexec/tkn/

### ISSUE THREAD

**Issue by chmouel** [tektoncd/catalog#728]
We are detecting plugins if they are : 

* $HOME/.config/tkn/
* or in $PATH

Should we support detection in /usr/libexec/tkn too ?

The idea is to have `vendors` being able to ship tkn plugin and not have it necessary exposed in PATH.

GIT supports PATH and /usr/libexec

NB: `/usr/libexec` should probably need to be overridable with a ldflags in Makefile for vendors who compiles tkn to overrides with custom path.

**Comment by vdemeester** [comment]
@chmouel is `/usr/libexec/{something}` usually in the `$PATH` ? My guess is that it is not usual to put these folder in PATH, so yeah, I think it would make sense 🙃 It's just an additionnal folder to check.
One question is also is there something similar on darwin and windows ?

**Comment by chmouel** [comment]
Probably not on darwin and windows.. but that doesn't really matter tho i think @vdemeester

**Comment by vdemeester** [comment]
@chmouel now that we support "in path" (right ?), I think this issue can be marked as obsolete.

**Comment by chmouel** [comment]
@vdemeester I think /usr/libexec is still a good idea for distributor where the plugin will be astracted
