### ISSUE TITLE
QA: How to use buildah and skopeo task with internal OpenShift registry with TLSVERIFY=true

### ISSUE THREAD

**Issue by csantanapr** [tektoncd/catalog#748]
# Expected Behavior

We are using OpenShift Pipelines Operators (aka Tekton).

We want to use buidlah and skopeo from a tekton task be able to pull, push, copy images from/to the OpenShift internal registry on the same Cluster the task is running.

The image URL looks like this `image-registry.openshift-image-registry.svc:5000/openfn-dev/web-app:02bb372`

The only way to get buildah and skopeo to work is using `TLSVERIFY=false` but this cause issues and doesn't look like a good solution.

We want to be able to provide the CA/trustchain of the internal OpenShift Registry into the Pod that teskton task is running buildah and skopeo.

Anyone knows how can we get the tekton task to trust and login into the internal OpenShift registry?

There are other container image tool we are trying to use `crane` to be able to copy images while retaining the digest, but `crane copy` doesn't support skip tls verify. Having a way to have this tools to trust the https/ssl of the internal registry would solve many issues we are having trying to implement CICD pipelines for OpenShift clients in the financial sector which they don't want to skip SSL verify.

Here is an issue I open on `crane` and the suggestion from the team is to get buildah, skopeo, crane to trust the https server of the internal registry. https://github.com/google/go-containerregistry/issues/1040

cc @imjasonh

**Comment by nikhil-thomas** [comment]
@vdemeester @piyush-garg

**Comment by piyush-garg** [comment]
Hey @csantanapr 

Which version of OpenShift Pipelines Operator you are using? Also can you please provide a bit of detail about the task and taskrun.Thanks

**Comment by csantanapr** [comment]
Hi using OCP 4.7
Using buildah task https://github.com/tektoncd/catalog/blob/main/task/buildah/0.2/buildah.yaml
