### ISSUE TITLE
Cannot connect to insecure private registry

### ISSUE THREAD

**Issue by rohitsakala** [tektoncd/catalog#757]
I am using https://github.com/tektoncd/catalog/blob/master/task/buildpacks/0.3/buildpacks.yaml. 

Here the `APP_IMAGE` doesn't take transport style like `http` or `https`. The `tekton` staging pod makes an `https` call to the registry whereas my registry is insecure. How do I tell `tekton` to make a `http` request ?

**Comment by vinamra28** [comment]
cc @jromero

**Comment by jromero** [comment]
@rohitsakala thank you for filing this issue. I've copied this issue to our development repo for this task and added a [reply](https://github.com/buildpacks/tekton-integration/issues/31#issuecomment-863290558).
