### ISSUE TITLE
Missing parameters for sonnarqube-scanner task

### ISSUE THREAD

**Issue by gbonnefille** [tektoncd/catalog#760]
# Expected Behavior

In corporate environment, with multibranch workflow, the sonnar scanner must receive some parameters like:
- -Dsonar.login
- -Dsonar.branch.name
- -Dsonar.branch.target

When working with pull-request model, we also expect:
- sonar.pullrequest.key
- sonar.pullrequest.branch
- sonar.pullrequest.base

# Actual Behavior

Only sonar.host.url is parametrized.

**Comment by zacheryph** [comment]
I wonder if this might be better resolved by having a way of merging the project sonar-project.properties and the one coming from sonar-settings

**Comment by gbonnefille** [comment]
> I wonder if this might be better resolved by having a way of merging the project sonar-project.properties and the one coming from sonar-settings

I think these sonar.pullrequest.* properties should be provided as var env as they are dynamic information: mostly different from one run to another, depending on external context.
