### ISSUE TITLE
sonarqube-scanner: settings from secret fails

### ISSUE THREAD

**Issue by zacheryph** [tektoncd/catalog#768]
# Expected Behavior

providing sonar-settings from a secret should get copied into the source-dir and work

# Actual Behavior

the settings _are not found_ when providing sonar-settings from a secret. this possibly affects configmap's as well.

# Steps to Reproduce the Problem

1. make a `PipelineRun` with the following

```yaml
  workspaces:
  - name: source
    ...redacted...
  - name: sonar-settings
    secret:
      secretName: sonar-properties
```

2. Observe
```
using user provided sonar-project.properties file
touch: cannot touch 'sonar-project.properties': No such file or directory
/tekton/scripts/script-0-vswrx: line 41: sonar-project.properties: No such file or directory
/tekton/scripts/script-0-vswrx: line 42: sonar-project.properties: No such file or directory
/tekton/scripts/script-0-vswrx: line 43: sonar-project.properties: No such file or directory
---------------------------
cat: /workspace/source-dir/sonar-project.properties: No such file or directory
```

# Resolution

The script does `cp -R ...` the sonar-project.properties. Since secrets get mounted as symlinks to `...some-dir-name` we actually copy a symlink. This needs to be updated to `cp -RL` to follow symlinks so you get the actual file contents copied before _possibly_ altering the host/project name.

# Additional Info

I can open a PR for this but not quite sure if I should/can edit `0.1` or create a ... `0.2` or `0.3`. Also I am not sure what to do since #590 is sitting open but stale.

**Comment by zacheryph** [comment]
Whoops. I accidentally referenced #760 at first, though it should be the PR #590

**Comment by babadofar** [comment]
Can confirm that this is a problem. Reading sonar-project.properties in from a  secret  and trying to override some values does not work with the current code base

**Comment by sanski** [comment]
I can confirm that this is a problem and that the PR solves it: https://github.com/tektoncd/catalog/pull/838
