### ISSUE TITLE
Tag Images for openshift-client Task

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/catalog#78]
Currently, the `openshift-client` task uses a tag of [latest](https://github.com/tektoncd/catalog/blob/master/openshift-client/openshift-client-task.yaml#L15) for its image. It would be a better practice to tag the image based on the version of Tekton pipelines the task would work with and explicitly call out what the version tag is for the task as opposed to using the `latest` tag.

There should be documentation on the available tags and how those tags correspond to certain versions of Tekton pipelines/the task. The previous versions of the task should also be archived and use the appropriate image tag.

This issue is in response to #74 where the task was updated for a new version of the OpenShift Tekton operator that is actually not available yet. I would like to ask that this task not be updated until the new version of an operator is available in the future.

**Comment by piyush-garg** [comment]
@danielhelfand We have reverted the change for openshift client task that broke for the operator, also we have tagged the image this time, soon we will do the archiving of task like releasing a branch or something else. This is in discussions now.
