### ISSUE TITLE
openshift-client on k8s(arm64) - exec format error

### ISSUE THREAD

**Issue by JCzz** [tektoncd/catalog#826]
Building on Kubernertes(Arm64) Running openshift-client.yaml from this [tutorial](https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/pipelines.html)

Error:
`[deploy-kubernetes-service : oc] 2021/09/27 10:25:47 Error executing command: fork/exec /tekton/scripts/script-1-bmp4n: exec format error`

Looks like the image:
`quay.io/openshift/origin-cli`
do not support arm64

**Comment by vdemeester** [comment]
As stated, currently the image used in the Task doesn't support any other platform than amd64, and the task is documented as such [here](https://github.com/tektoncd/catalog/blob/main/task/openshift-client/0.2/openshift-client.yaml#L13).
/close
