### ISSUE TITLE
github-set-status: Allow TLS deactivation and usage of custom CA bundle

### ISSUE THREAD

**Issue by mpreu** [tektoncd/catalog#832]
# Expected Behavior
Task `github-set-status` can be executed with TLS deactivated to work with Github-Enterprise instances reachable over `https` and self-signed certificates. It would also be great if the task accepts custom certificates as an input (e.g. via a secret / workspace).

# Actual Behavior
TLS cannot be explicitly deactivated in the task. I have no possibility to add custom certificates either.

# Steps to Reproduce the Problem

1. Execute task against Github Enterprise instance over `https` and a self-signed certificate.

**Comment by jandradap** [comment]
It would be very nice if CA could be specified in the different tasks.
