### ISSUE TITLE
SonarQube scan login paramenters

### ISSUE THREAD

**Issue by krishnaraman001** [tektoncd/catalog#837]
# Expected Behavior
should have possibility to provide login parameters or secret to the sonarqube scan task in tekton
# Actual Behavior
Dont know where we have to provide authentication related details in the task.

Can some one help me,  how to provide token or login, password to this sonarqube task?
i see the PR #590  is still not merged, are we going to do that soon?

**Comment by babadofar** [comment]
Perhaps this helps - You can add an env parameter with SONAR_TOKEN . 
- create   secret named sonarlogin containing  the token 
 
``` 
kubectl create secret generic sonarlogin --from-file=sonarlogin
```

add it to the pipeline

```      
    stepTemplate:
          env:
          - name: SONAR_TOKEN
            valueFrom:
              secretKeyRef:
                name: sonarlogin
                key: sonarlogin

**Comment by krishnaraman001** [comment]
@babadofar that is not working 
![image](https://user-images.githubusercontent.com/28945373/137850337-6e7345af-5b09-4510-bc7c-94165cf17c43.png)

got an error like this

**Comment by jandradap** [comment]
> @babadofar that is not working ![image](https://user-images.githubusercontent.com/28945373/137850337-6e7345af-5b09-4510-bc7c-94165cf17c43.png)
> 
> got an error like this

It looks like a syntax error, can you attach the full pipeline and I'll take a look at it?
