### ISSUE TITLE
How to speed up git clone

### ISSUE THREAD

**Issue by BigFatDog** [tektoncd/catalog#885]
Hello,
Currently I'm using `git-clone` and it works fine in my pipeline. However, it is slow to clone the git repo each time I run the pipeline becuase:
1.  My Tekton task pod has slow internet connection to my git repo, which is bitbucket
2.  My repo is large,  `git-clone` runs a fresh clone start over each time.

Is there a way to speed up this like:
1. keep the workspace of `git-clone`
2. re-use the workspace in other pipeline runs
3. do incremental `git pull` in other pipeline runs

I checked Tekton doc and found `PipelineResource`, it might be a solution but it already gets deprecated. 

Any suggestions? Thank you.

**Comment by gujiwork** [comment]
I also encountered such a problem, when my repository is very large, several GB, git clone becomes very slow

**Comment by zaxiong** [comment]
Me too
