### ISSUE TITLE
Releasing process of the catalog

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/catalog#96]
With the recent backward-incompatible (`containerTemplate` -> `stepTemplate`, templating using `$(…)` instead of `${…}`), the catalog is or appeard broken for different releases of tektoncd/pipeline.

This issue is there to discuss what we can do to, hopefully fix that.

One solution would be to branch the catalog on a given cadence with the same major/minor version of tektoncd/pipeline – making, for example, the 0.6.0 catalog branch be compatible with tektoncd/pipeline 0.6.0 for sure.

The rules would be the following:
- Once we do a [`tektoncd/pipeline`](https://github.com/tektoncd/pipeline) release
  - we make sure all task from the catalog works with it (aka validate and are able to run) — *initially this might be done manually, but parallel work should be done to automate those tests* (see #102 )
  - we create a branch with that working state, that is guaranteed to work on the said release
  - we update the previous release branch `README` to inform that it's not supported anymore
- The `master` branch can be updated alongside changes from [`tektoncd/pipeline`](https://github.com/tektoncd/pipeline)
- If a new task is added, we can also cherry-pick to the latest release branch (and only this one to reduce the maintainance burden) — this is up to the author of the task and/or the main repository OWNERs

**Another alternative could be "Design a system for annotating Tasks with Tekton version support"**

Some tasks in the catalog may only work with recent or old versions of Tekton. We should come up with a clear way to display this to catalog users.

/kind feature
/area release

**Comment by vdemeester** [comment]
I'm gonna add the content of #53 in here

**Comment by vdemeester** [comment]
I think, this is definitely not relevant anymore with the current catalog organization.
/close

**Comment by bobcatfish** [comment]
> Another alternative could be "Design a system for annotating Tasks with Tekton version support"

and i think we did that! 😎
