### ISSUE TITLE
Buildah & BUILD_EXTRA_ARGS

### ISSUE THREAD

**Issue by johnlongo** [tektoncd/catalog#978]
Tring to pass custom registry using BUILD_EXTRA_ARGS (see below) but getting and error (see below) when I try to run it. The message is "No options (--format=oci) can be specified after the image or container name" and not sure how to resolve. Anyone have any ideas on how to fix this issue? I'm using the latest version https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.3/buildah.yaml

![image](https://user-images.githubusercontent.com/23619505/169705848-5652d53e-60df-4e72-813e-37d3442463db.png)

![image](https://user-images.githubusercontent.com/23619505/169705889-0a39a05b-3a4c-4b80-8df5-b45a7226a263.png)

![image](https://user-images.githubusercontent.com/23619505/169705907-f50e1240-16b9-428e-a134-43cdae232c76.png)

![image](https://user-images.githubusercontent.com/23619505/169705932-54fc9075-6d5a-4523-bb9b-1064d90daaea.png)

**Comment by vdemeester** [comment]
Hey @johnlongo, the `BUILD_EXTRA_ARGS` is argument for `buildah bud`. This means it's not "assumed" it is `build-arg` or anything. Using `--build-arg=REGISTRY=…` should however work 🤞🏼

**Comment by KIRY4** [comment]
Hey @vdemeester so I correctly understood that BUILD_EXTRA_ARGS not equal --build-arg arg=value?? From https://man.archlinux.org/man/community/buildah/buildah-bud.1.en
